### PR TITLE
Mangroves clean

### PR DESCRIPTION
**Pull request by cbur24**
### Proposed changes
Notebook examining change in mangrove extents between years.  A refinement of the ARDC notebook that does a similar analysis, though in this iteration satellite images are tidally filtered before image compositing. 

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell and re-use tags if possible
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Comment by fangfy** [comment]
Adding the tidal height constraint is really nice! however, I don't think this addresses issue #144 on shapefile download? I'm wandering whether it's possible to add an optional step to download and intersect the GWM layer within the notebook?

**Comment by cbur24** [comment]
Thanks @fangfy. I agree it would great if we could automatically download the GMW file and clip it to a user defined box, but the the GMW shapefile is >800mb so its a lot of data to download.  And the African extent of the GMW shapefile is >140 mb so I don't think we should have it on the Sandbox.  If you know of a solution then happy to see it implemented.

**Comment by fangfy** [comment]
The GWM zipfile is about 177M (compressed). So I think it's OK to download (as an optional step to run at least). Something like following should work but I don't have a work around to deal with uncompressed filesize. Also we need to add this url to the whitelist. I'm currently testing from NCI.

```
import requests
import shutil
from zipfile import ZipFile

def download_and_unzip_gmw(url='https://wcmc.io/GMW_2016'):
    local_filename = url.split('/')[-1]
    with requests.get(url, stream=True, allow_redirects=True) as r:
        with open(local_filename, 'wb') as f:
            shutil.copyfileobj(r.raw, f)
    with ZipFile(local_filename) as z:
        z.extractall()
        shapename = [f for f in z.namelist() if f.endswith('.shp')][0]
    return shapename

gmw_shp = download_and_unzip_gmw(url)

# intersect with ROI

```

**Comment by fangfy** [comment]
another option is to burn this shapefile into a cog (int8 raster) and put int S3...

**Comment by cbur24** [comment]
Converting it into COG saves a lot of steps...+1 for that idea

**Review by fangfy — APPROVED** [review]

**Pull request merged**
