### PR TITLE
Waterbody vis

### PR DESCRIPTION
**Pull request by mickwelli**
### Proposed changes
New RWE notebook showing two animations for waterbodies.

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [X] Include relevant tags in the first notebook cell and re-use tags if possible
- [X] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Review by nanaboamah89 — CHANGES_REQUESTED** [review]
Getting this error, not able to proceed 
Screenshot 2024-09-02 100013
Screenshot 2024-09-02 100035

**Review by nanaboamah89 — APPROVED** [review]

**Comment by nanaboamah89** [comment]
After rerunning the notebook, it's working. Bravo @mickwelli.

**Review by vikineema — APPROVED** [review]

**Comment by mickwelli** [comment]
Split this into 2 notebooks and added further examples, requesting re-review from @nanaboamah89

**Comment by nanaboamah89** [comment]
@mickwelli , I have gone through the notebooks. For the Waterbodies Seasonal Animations notebook Instead of having two examples in the notebook, having one example is fine, and in the conclusion or at the analysis parameter section, we can let the use know they can run test it Bakolori Dam by providing the latitude and longitude to them an example.

**Comment by lisarebelo** [comment]
Thanks Michael, the notebooks look good with two different examples of how the timeseries data can be used and visualised.

Notebook 1: Seasonal animations
A couple of minor edits:
- Analysis parameters - "water extent over a shorter time period" (change shorter to short)
- Inspect timeseries - might be useful to add explanation for geohash listing/identification (and add link to waterbodies documentation and dataset notebook)

For the timeseries with rainfall - can you increase offset between the two parameters (i.e. increase max value of each axis) for both occurrences of the graph.

I still feel there is too much changing (3 things) to fully interpret what is happening in the animation. and recommend keeping the chart parameters static but indicating where in the timeseries the the geomad corresponds to

Notebook 2: long term
Can you check the geometry of the annual WOfS in the animation - it looks stretched S-N compared to the summary above

**Comment by mickwelli** [comment]
Thanks @lisarebelo, I've made the following revisions:

Long term notebook:
* Added fixed aspect ratio to plots and animation, WOfS was actually stretched E-W, it's a bit illusory.

Seasonal notebook:
* Added text under Inspect Timeseries providing background on the Waterbodies service, linking to Datasets notebook and docs.
* Edited analysis parameters text.
* Increased space on y axes for animation
* Tried to overcome visual crowding by having the charts static in transparent aesthetic, with solid lines and bars coming in with animation to show timing. Interested in your thoughts on this.
* Fixed up data referencing issue for Bakolori Dam, I think it's quite a neat example now.

**Review by lisarebelo — APPROVED** [review]

**Pull request merged**
