### PR TITLE
EVI notebook

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes
Include a brief description of the changes being proposed, and why they are necessary.
Created an Enhanced Vegetation Index Notebook 
1. Load sentinel 2 image
2. Calculate the EVI 
3. Plot the Results

### Checklist (replace `[ ]` with `[x]` to check off)
- [X ] Remove any unused Python packages from `Load packages`
- [ X] Remove any unused/empty code cells
- [X ] Remove any guidance cells (e.g. `General advice`)
- [ X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [ X] Include relevant tags in the first notebook cell and re-use tags if possible
- [X ] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [ X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Review by lisarebelo — COMMENTED** [review]
Please change link to point to the one below, rather than a blog which may not have scientifically correct details. It is always best to quote an original source:

https://www.usgs.gov/landsat-missions/landsat-enhanced-vegetation-index#:~:text=Landsat%20Enhanced%20Vegetation%20Index%20(EVI,in%20areas%20with%20dense%20vegetation.

Delete the first two sentences below as the information is repeated in the next paragraph:
(EVI) is similar to Normalized Difference Vegetation Index (NDVI) and can be used to quantify vegetation greenness. However, EVI corrects for some atmospheric conditions and canopy background noise and is more sensitive in areas with dense vegetation.  Whereas the NDVI is sensitive to chlorophyll, the EVI is more responsive to canopy structural variations, including Leaf Area Index (LAI), canopy type, and canopy architecture. The two vegetation indices complement each other in vegetation studies and improve upon the detection of vegetation status, changes and characteristics.

Change the next paragraph to:
The Enhanced Vegetation Index (EVI) can be calculated from Landsat or Sentinel-2 images, and is similar to the Normalized Difference Vegetation Index (NDVI), as it quantifies vegetation greenness.  However, the EVI corrects for some atmospheric conditions and canopy background noise and is more sensitive in areas with dense vegetation.

Change the next sentence to the following:
Using Digital Earth Africa's archive of analysis-ready satellite data, we can easily calculate the EVI for mapping and monitoring vegetation through time, or as inputs to machine learning or classification algorithms.

Change the 3 points to:
1. Load Sentinel 2 images for an area of interest (AOI)
2. Calculate the Enhanced Vegetation Index (EVI)
3. Visualize the results.

Change "Calculting EVI using the calculate_indeces" to:
Calculating the EVI using the calculate_indices function

The index needs further explanation - the formula is not correct. Change "The Enhanced Vegetation Index requires the red, nir and blue bands" to:
"The Enhanced Vegetation Index requires the red, nir and blue bands as well as an “L” value to adjust for canopy background, “C” values as coefficients for atmospheric resistance", and a gain factor (G).

Please present the index as:
"EVI = G * ((NIR - R) / (NIR + C1 * R – C2 * B + L))"

How the index is currently written, the 2.5 x is in the wrong place (note that it is outside of the double brackets). Check the website link given above.

**Comment by nanaboamah89** [comment]
> Please change link to point to the one below, rather than a blog which may not have scientifically correct details. It is always best to quote an original source:
> 
> https://www.usgs.gov/landsat-missions/landsat-enhanced-vegetation-index#:~:text=Landsat%20Enhanced%20Vegetation%20Index%20(EVI,in%20areas%20with%20dense%20vegetation.
> 
> Delete the first two sentences below as the information is repeated in the next paragraph: (EVI) is similar to Normalized Difference Vegetation Index (NDVI) and can be used to quantify vegetation greenness. However, EVI corrects for some atmospheric conditions and canopy background noise and is more sensitive in areas with dense vegetation. Whereas the NDVI is sensitive to chlorophyll, the EVI is more responsive to canopy structural variations, including Leaf Area Index (LAI), canopy type, and canopy architecture. The two vegetation indices complement each other in vegetation studies and improve upon the detection of vegetation status, changes and characteristics.
> 
> Change the next paragraph to: The Enhanced Vegetation Index (EVI) can be calculated from Landsat or Sentinel-2 images, and is similar to the Normalized Difference Vegetation Index (NDVI), as it quantifies vegetation greenness. However, the EVI corrects for some atmospheric conditions and canopy background noise and is more sensitive in areas with dense vegetation.
> 
> Change the next sentence to the following: Using Digital Earth Africa's archive of analysis-ready satellite data, we can easily calculate the EVI for mapping and monitoring vegetation through time, or as inputs to machine learning or classification algorithms.
> 
> Change the 3 points to:
> 
> 1. Load Sentinel 2 images for an area of interest (AOI)
> 2. Calculate the Enhanced Vegetation Index (EVI)
> 3. Visualize the results.
> 
> Change "Calculting EVI using the calculate_indeces" to: Calculating the EVI using the calculate_indices function
> 
> The index needs further explanation - the formula is not correct. Change "The Enhanced Vegetation Index requires the red, nir and blue bands" to: "The Enhanced Vegetation Index requires the red, nir and blue bands as well as an “L” value to adjust for canopy background, “C” values as coefficients for atmospheric resistance", and a gain factor (G).
> 
> Please present the index as: "EVI = G * ((NIR - R) / (NIR + C1 * R – C2 * B + L))"
> 
> How the index is currently written, the 2.5 x is in the wrong place (note that it is outside of the double brackets). Check the website link given above.

Thanks for the correction, I have modified the index calculation also from the calculate indices

**Review by lisarebelo — CHANGES_REQUESTED** [review]
In the Background section remove the square brackets from the first line:
> [Enhanced Vegetation Index]

The first half of the notebook uses Sentinel 2, the second half uses Landsat. 
E.g. from Ln 6:
> Here, we use satellite_mission='ls' since we're working with Landsat 9.
Please change to be consistent and use Sentinel 2 in all examples.

There is an error in the comment in Ln 6, please change to EVI:
> # Calculate NDVI using `calculate indices`

Under section Plot the EVI Time Series, change:
> To have an idea of the vegetation health changes
to:
>  To understand changes in vegetation

Change the title of the graph to "Zonal mean of the EVI"

Delete the backslash and edit the description:
> Plot individual image to verify why some timestep has a low EVI values\
to:
> Plot an individual image to view the spatial variations in EVI

**Review by mickwelli — CHANGES_REQUESTED** [review]
As per comment above, please check min_gooddata argument

**Review by lisarebelo — APPROVED** [review]
Check the link - it is not displaying properly in the notebook - please remove the square brackets and embed the link.

**Review by mickwelli — APPROVED** [review]
Great notebook!

**Pull request merged**
