### PR TITLE
Wetlands Insight Tool in French

### PR DESCRIPTION
**Pull request by andrewdhicks**
### Proposed changes
Adds a French translation to the Wetlands Insight Tool widget

Instructions on how translation works added to [Tools/README.md](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/wit_fr/Tools/README.md)

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell and re-use tags if possible
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Review by caitlinadams — CHANGES_REQUESTED** [review]
Thanks for working on this, Andrew. It's looking great -- the only issue was that the translation file didn't install when I pip installed the deafrica-tools package. We fixed that by adding -e to the pip install, but this will need to be addressed for the sandbox install process.

Once we get that working, I can confirm that the app runs smoothly, and all the translations appear correctly (to the best I can tell with my non-existent French vocabulary). Happy to approve once you've updated the package to ensure non-python files get included.

Awesome work!

**Comment by caitlinadams** [comment]
@andrewdhicks -- do you have an update on whether you were able to resolve the inclusion of the translation files? It would be great to merge this in if all the work is done.

**Comment by andrewdhicks** [comment]
@caitlinadams The translation file is now included in the python package, so this is now ready to go. I'll improve the translation process in another PR.

For the automated upload check to pass, the POEditor API key will need to be added as a repo secret by a repo admin (@alexgleith or @fangfy), who I'll contact via slack.

**Review by caitlinadams — APPROVED** [review]
Fantastic, thanks Andrew!

**Pull request merged**
