### PR TITLE
Unbanization

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes
Urbanization python file ongoing.

### Closes issues (optional)
- Closes Issue #000
- Closes Issue #000

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell and re-use tags if possible
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Comment by amit1rrr** [comment]
Sorry to intrude but I noticed this PR contains Jupyter notebook files that are hard to review on GitHub due to the JSON diffs.

You might want to checkout [ReviewNB](https://www.reviewnb.com/), code review tool for notebooks. Provides visual diffs & commenting for Jupyter notebooks on GitHub. Completely free for open source repositories.

Disclaimer: I built ReviewNB

diff_and_commenting

**Comment by cbur24** [comment]
I think this notebook should be in the `Real_world_examples` folder rather than the `Frequently_used_code`

**Comment by caitlinadams** [comment]
Hi @nanaboamah89,

This is getting really close to being done. I think there are a few more steps to complete. 

- It would be best to move this notebook into the Real-world examples folder. You may want to do this as part of a new pull request since a couple of rogue files have made it into this one. To do that, download a copy of the notebook, make a new branch from master, and re-upload the finished notebook. Then make a new pull request from that branch. You can also just title the notebook "Urbanization" rather than "DEA_urbanization".
- In the "Background" section, it would be really great to have a paragraph on why measuring urbanization is interesting/valuable. To see an example, have a look at the text in the [Chlorophyll notebook](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/blob/master/Real_world_examples/Chlorophyll_monitoring.ipynb). You could then move the current text you have in the "Background" section into the "Description" section.
- When you get to loading data, I'm not sure you gain that much by writing and using the `compute_ds` function, seeing as it's a wrapper around load_ard. However, I understand that you've done this to make it easier to load the necessary data for two years. I spoke to @cbur24 and we think that it would be worthwhile making a function that can more easily compute the geomedian, like what you've written in this and the Mangroves notebook. We can talk further about how to approach this.
- When you plot the two rgb images, it would be nice to do them side-by-side. I think this would be possible if the geomedians were contained in a single `xarray` indexed by year. We'd need to work out how to do this though. 
- I think it would be valuable to add some more Markdown headers and explanation throughout your notebook, so that a new user can follow what you're doing. For example, before cell 15, it would be good to have a header saying "Calculate urbanisation indices", then some description of the indices you're calculating
- You plot both NDBI and BUI -- it might be worth discussing in markdown the similarities/differences that the user might notice in the plot. You also use a thresholding value of `-0.1` when making these plots; it would be helpful to explain why to the user using markdown
- I'm not sure that your area calculations are working, since when you do the plot, it looks like all the pxiels are there. Let's look at this together and see if we can work out what's going on -- this might explain why your two pixel counts in the histogram are the same for other years?
- once the analysis is finalised, it would be great to add a conclusion explaining to the user what they should learn from the analysis, and how the can change it to a new area. Many of the real-world example notebooks contain this, so you should be able to get some inspiration from those.

**Comment by andrewdhicks** [comment]
@caitlinadams I've updated the plots, but getting confusing results when plotting the comparison between years. Chat Monday?

**Pull request closed without merging**
