### PR TITLE
Kenya Drought Index Use Case

### PR DESCRIPTION
**Pull request by vikineema**
### Proposed changes
First drafts of the notebooks for the Kenya Drought Index Use Case. 

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [ ] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [x] Include relevant tags in the first notebook cell and re-use tags if possible
- [x] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Review by fangfy — COMMENTED** [review]
On the rainfall anomaly, the anomaly over entire county should be calculated relative to mean and std over entire county. I.e. 

`# Monthly means for entire area
climatology_mean_county = ds_rf_m.groupby("time.month").mean(["x", "y"]).mean("time").compute()
`
`# Monthly std dev. for entire area
climatology_std_county = ds_rf_m.groupby("time.month").mean(["x", "y"]).std("time").compute()
`
`# standardised anomalies for the county
standardised_anomalies_county = xr.apply_ufunc(
    lambda x, m, s: (x - m) / s,
    ds_rf_x.groupby("time.month").mean(["x", "y"]),
    climatology_mean_county,
    climatology_std_county,
    output_dtypes=[ds_rf_x.rainfall.dtype],
    dask="allowed",
).compute()
`

Have a figure showing this anomaly value for all counties for a few months will be nice.

If multiple counties can be plotted. It will be useful to plot both standardized anomaly and anomaly (in unit of mm rainfall).

**Review by fangfy — COMMENTED** [review]
On the wofs anomaly, suggest calculate extent every 3 months, i.e. some like

`wofl = dc.load(product="wofs_ls", fuse_func=wofs_fuser,
                collection_category='T1', **query)
wet = masking.make_mask(wofl.water, wet=True) 
dry = masking.make_mask(wofl.water, dry=True)
nwet = wet.resample(time='QS-JAN').sum()
ndry = dry.resample(time='QS-JAN').sum()
nobs =nwet+ndry
freq = nwet/nobs
'
'#select use starting month of the quarter/season
ds_wofs = freq[freq.time.dt.month==season_start].compute().to_dataset(name='frequency')
`

I'd probably increase the cut-off frequency to 0.5 as there are less observations within a season.

If this is done, potentially the rainfall should also be calculated over 3 months. E.g.
`# Monthly means (after setting the correct nodata value to nan)
climatology_mean = ds_rf_m.resample(time="QS").sum(skipna=False).groupby("time.quarter").mean("time").compute()
`
Here's some comparison: https://earlywarning.usgs.gov/fews/product/599
There's no standardized anomaly but the percentage pattern looks consistent to me.

**Comment by vikineema** [comment]
> Have a figure showing this anomaly value for all counties for a few months will be nice.
> 
> If multiple counties can be plotted. It will be useful to plot both standardized anomaly and anomaly (in unit of mm rainfall).

For the rainfall anomalies notebook, the second version (01_1_Rainfall_anomaly_CHIRPS.ipynb) is able to derive the rainfall anomalies for all the counties in order to have a figure showing the rainfall anomaly values for all counties for a few months both standardized anomaly and anomaly (in unit of mm rainfall).

**Review by fangfy — COMMENTED** [review]
A few questions and comments for the drought index:
* A reference to the method used will be helpful and perhaps some background information on the method
* what's the period of interest (IP in the equation)? is it the current year? or a fixed number of months?
* An additional normalisation is applied (I believe to scale the index within the AOI to between 0 and 1) which should also be explained in the text? does this impact monthly by month comparison?
* At the moment, each notebook calculate and one index. It's hard to see the correlation between the different parameters. It will be helpful to show different index or anomaly (i.e. rainall, temperature, vegetion etc) in on figure side by side for a month (or season).

**Comment by vikineema** [comment]
@fangfy @nanaboamah89 I've combined the individual notebooks into one notebook to be able to address some of the comments above, in the most recent commit.

> A few questions and comments for the drought index:
> 
>     * A reference to the method used will be helpful and perhaps some background information on the method
> 
>     * what's the period of interest (IP in the equation)? is it the current year? or a fixed number of months?
> 
>     * An additional normalisation is applied (I believe to scale the index within the AOI to between 0 and 1) which should also be explained in the text? does this impact monthly by month comparison?
> 
>     * At the moment, each notebook calculate and one index. It's hard to see the correlation between the different parameters. It will be helpful to show different index or anomaly (i.e. rainall, temperature, vegetion etc) in on figure side by side for a month (or season).

**Pull request closed without merging**
