### PR TITLE
Lake Baringo grazing use case

### PR DESCRIPTION
**Pull request by eefaye**
**Title:** Grazing in the conservancy around Lake Baringo.

**Aim:**
Using earth observations data to prevent pasture conflict, by monitoring the vegetation and water extent of areas that can lead to pastures conflict and protect the wildlife within the region.

**Study area:**
image

**Scope:**
1.	To generate a historical trend analysis of vegetation within the Conservancy. This will aid in identifying the peak season trends where there is high vegetation index.
2.	To determine the extent of the water bodies
3.	Prosopis cover mapping: invasive species – Further research 

**Input Data and expected outputs:**
- Input shapefile for the area of interest: `Ruko_Shapefiles.shp`
- Temporal extent: Sentinel 2, 2017 – to date.
- Generate a 1D zonal mean, smoothed line plot comparing each years profile of EVI
           -  Indicate the Start Of Season (SOS), Peak Of Season (POS), and End Of Season (EOS) on the graph for each year
- Generate one-dimensional (zonal mean) phenology statistics for each year (csv?)
- Stretch: generate two-dimensional phenology statistics for each year
- **Must run on default Sandbox**

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] 1-D EVI graphs - smoothed and interpolated, with basic pheno stats indicated
- [x] One-dimensional (zonal mean) phenology statistics for each year (csv)
- [x] Runs on the default sandbox

### Notes
**Ideas to optimise for default sandbox**
 - Use dask
 - Split into multiple notebooks - i.e. processing (save output) and plotting
 - Downsample S-2 data - reduce temporal/spatial resolution
 - Use smaller shapefiles that highlight areas of interest

### CODE REVIEW

**Comment by nanaboamah89** [comment]
Nice work done; we are on the right track. I got the error below when I tried to run it in the sandbox. 

Capture

**Comment by nanaboamah89** [comment]
Day of Year: can it show the months instead if number at the x-axis.

Capture_1

**Comment by cbur24** [comment]
@nanaboamah89 To plot the months is quite messy because the phenology results come back as the DOY (which nicely allows for plotting each year on the same axis, as opposed to plotting with time which is unique for each year).  Instead, I've labelled the phenology annotations with the year and month.  Is this acceptable?

image

**Comment by eefaye** [comment]
I've not generated automatic tables in Python before but this data looks like a table to me. I think the floating points with dates make the line graph a little more confusing.

| Year | SOS| POS | EOS |
|-------|------|-----|-----|
|**2017**| March | December | December|
|**2018**| February | July | December |
|**2019** | April | August | November |
|**2020**| April | August | December|

**Comment by brianterry-ama** [comment]
@cbur24 just use 
`plt.xticks(np.linspace(0,365,13)[:-1], ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'))`

**Comment by cbur24** [comment]
> 
> 
> I've not generated automatic tables in Python before but this data looks like a table to me. I think the floating points with dates make the line graph a little more confusing.
> 
> e.g.
> Year 	SOS 	POS 	EOS
> **2017** 	March 	December 	December
> **2018** 	February 	July 	December
> **2019** 	April 	August 	November
> **2020** 	April 	August 	December

I agree the tables make sense. The phenology data is currently exported as tables (csvs). I just pushed up a new edition, feel free to check it out and make whatever changes you think make sense.

**Comment by brianterry-ama** [comment]
Also its strange that only 2017 seems to be starting at the correct point

**Comment by cbur24** [comment]
> 
> 
> Also its strange that only 2017 seems to be starting at the correct point

I think its to do with the resampling; where the datetime label sits with respect to the available satellite image dates.

**Comment by cbur24** [comment]
@brianterry-ama Can you please add the water extent notebook to this PR? Would be nice to have everything in the one place

**Comment by cbur24** [comment]
@eefaye @brianterry-ama @caitlinadams @nanaboamah89 

FYI I am going to start working on a draft of a 2D phenology notebook now, and I'll leave the refinement of the 1D phenology notebook to yourselves

**Comment by cbur24** [comment]
@nanaboamah89 Per-pixel phenology notebook has been added. Just calculates the result for a single year e.g. '2018', so needs to be re-run for each year of interest. This is the output:

image

**Comment by cbur24** [comment]
@nanaboamah89 refined the 1D phenology plot further

image

**Comment by nanaboamah89** [comment]
@brianterry-ama for the Water_Extent_Shape.ipynb. The water extent notebook was runed on Lake Bosomtwi.

From the time series analysis, 2019-09 had Zero water area due to cloud. Can that be avoided? 

graph

maximum_water_extent

**Comment by nanaboamah89** [comment]
Comments from Mohammed. 

> In the phenogy CSV file - now we have SOS, POS, EOS, and my wish is to generate stat report for all the 10-phenology metrics. 'SOS','vSOS','POS','vPOS','EOS','vEOS','Trough','LOS','AOS','ROG','ROS'

> I like DEA platform - help us do adaptive management - learn from data and act promptly

**Comment by cbur24** [comment]
@nanaboamah89 I updated the 1D pehnology notebook to print and export all the phenology statistics. I've also moved the entire folder `'Lake_baringo_grazing'` into a new folder at the top of the repo called `'Use Cases/'`.  This is where we will store use case notebooks and data from now on.  Let us know when these notebooks are ready and fit-for-purpose and then we can merge them into master

**Comment by cbur24** [comment]
@nanaboamah89 I refined the water-extent notebook in attempt to make it more robust, please let me know what you think.  It does fewer things now (no RGB animations or plotting - helps a lot with memory and speed), but it does fewer things better in my opinion. The notebook now resamples the datasets to _seasonal_ medians, this ensures that you don't get periods where cloud obscuring the water body results in the notebook claiming the masked out waterbody is at its 'lowest' area (when in fact we just can't see it).  This does mean you only get four water extents calculated per year, but the results still show the broad trends (and the results are accurate). For Lake Baringo, this is the trend:

image

The notebook is now called: `Water_Extent_Shape_refined_draft.ipynb`

**Comment by nanaboamah89** [comment]
Thank you @cbur24 for the water extent shape_refined notebook. It works great at my end and also when i tried it with other water bodies, the results was great.

**Comment by cbur24** [comment]
Ready for a review @caitlinadams @nanaboamah89

**Review by nanaboamah89 — COMMENTED** [review]
I am fine with it.

**Review by caitlinadams — APPROVED** [review]
Fantastic work, everyone. This is a great collection of notebooks!

**Pull request merged**
