### PR TITLE
add rollingGEOMAD

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes
Include a brief description of the changes being proposed, and why they are necessary.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [x] Include relevant tags in the first notebook cell and re-use tags if possible
- [x] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Review by fangfy — APPROVED** [review]
Some minor text edits.

**Review by fangfy — APPROVED** [review]

**Review by lisarebelo — CHANGES_REQUESTED** [review]
Under Background section please change:
> Satellite imagery allows us to observe the Earth with significant accuracy and detail
to:
> Satellite imagery allows us to observe the Earth in a repetitive and detailed manner

> The Digital Earth Africa (DE Africa) sentinel-2 Rolling GeoMAD (Geomedian and Median Absolute Deviations) is the Geomedian and MADs calculated over moving window of 3 months
to:
> The Digital Earth Africa (DE Africa) Sentinel-2 Rolling GeoMAD (Geomedian and Median Absolute Deviations) service provides monthly Geomedian and MADs calculated using a moving window of 3 months

> Each product combines measurements collected over a 3-month period to produce one representative, multi-spectral image for every pixel of the African continent.
to:
> Each product combines measurements collected over a 3-month period to produce one representative, multi-spectral image for every pixel of the African continent for each calendar month.

Under Important details the link provided does not include the rolling geomedian. Please create a separate PR to update the Docs page to include the rolling (monthly) product, in particular under "Specifications"

Under Description change:
> In this notebook we will work with Sentinel-2 Rolling GeoMAD and NDVI Anomaly.
to:
> In this notebook we will work with the Sentinel-2 Rolling GeoMAD and Mean NDVI and Anomalies products.

Under Load monthly mean NDVI data, change:
> Refer to the NDVI Anomaly notebook for more information NDVI mean.
to:
> Refer to the NDVI Anomaly notebook for more information on the DE Africa Mean NDVI and Anomalies product

**Review by mickwelli — COMMENTED** [review]
Hi @nanaboamah89 I have made some minor edits and think it would be good to add a further example for a cloud prone area showing the value of the MADs for change detection. I am thinking a tea plantation in Rwanda would be good showing harvest time.

In the meantime I noticed a more important issue - the time tags on the `gm_s2_annual` appear to be erroneous e.g. when ("2021-01", "2021-12") is specified there are images from "2020-12" and "2022-01" in the 'ds'. I can't reproduce this with other products e.g. the NDVI monthly mean which you've used in this notebook. Wondering if @fangfy has any insights? Thanks!

**Comment by fangfy** [comment]
@nanaboamah89 @mickwelli the new example is showing noise from missed cloud. Shall we keep the orginal example? or find another location where cloud impact is smaller?

If we want to showcase MADs, some more explanations on what the MADs are showing and how it can be interpreted are needed. I suppose the MADs might pick up different harvest patterns within a 3 month window - so e.g. can be used for crop classification? The timeseries of MADs is a bit tricker to interpret, i.e. hard to compare MADs from one period to another.

> Hi @nanaboamah89 I have made some minor edits and think it would be good to add a further example for a cloud prone area showing the value of the MADs for change detection. I am thinking a tea plantation in Rwanda would be good showing harvest time.

**Review by mickwelli — COMMENTED** [review]
Thanks @fangfy and @nanaboamah89. I've changed the study site to overcome cloud issues and added a diagram explaining the loading behaviour. I've also visualised SMAD, see what you think...

**Comment by nanaboamah89** [comment]
Hi @mickwelli, Great work in adding the diagram to it. One thing I noticed; we can talk about it in a meeting.
1. The x-axis should start from December 2020, December covers December to February, then we will have the overlap, in January 2021. Because a time was provided "2021-01-01 - 2021-03-31", if we stick to this it will be clear. or better still we November starts but the focus will be on January not December.

For instance, 
December 2020 QR GEOMAD -> December 2020, January 2021, Feb 2021
January 2021 QR GEOMAD -> January 2021, Feb 2021, March 2021,
If one loads January 2021 QR GEOMAD because the is intercept between in January 2021, December 2020 rolling GEOMAD will also be loaded.


The example in the Dealing with time below if January 2021 can be used instead of December as that will talk to the diagram.
For example, the December 2020 GeoMAD includes images from November and December 2020, and January 2021, so will be loaded as part of the 2021-01-01 - 2021-03-31 query. The date label in the loaded dataset will be 2020-12-16.

**Comment by mickwelli** [comment]
Thanks @nanaboamah89. As discussed, confirming the diagram correctly represents the geomedian loading behaviour.

**Review by mickwelli — APPROVED** [review]

**Review by lisarebelo — APPROVED** [review]
The notebook is a good demonstration of data loading for the rolling GM, thanks for all of the changes.

Please edit the product description:
> Date-range: October 2020 – present
To January 2019 - present

**Pull request merged**
