### PR TITLE
Add first and last composite examples

### PR DESCRIPTION
**Pull request by andrewdhicks**
### Proposed changes
Adds examples for making composites using `first` and `last`

### Checklist
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell and re-use tags if possible
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Comment by andrewdhicks** [comment]
Possible issues:
* Pulling in functions from xarray internals (`xarray.core.duck_array_ops`)
* Not showing examples of using these functions for `groupby` and `resample`, because I can't think of any use cases
* In the final 2 plots, I don't know how to add titles with `rgb`, so I'm doing an ugly print statement
* Haven't found a time period that shows a good example for before and after
* Need to add into text to _Time-based composites_ and _Most-recent composite_ sections 
* Need to add to top _Description_

**Comment by robbibt** [comment]
This looks like a fantastic notebook @andrewdhicks , will be great to have this in DEA Notebooks too. Just a question for my own benefit: are the "Before and after composites" composites calculated per-pixel (e.g. the latest valid observation per pixel accounting for missing/invalid data), or based on the entire time-step acquisition time (just the closest previous/subsequent timestep)?

**Comment by andrewdhicks** [comment]
@robbibt The composites are per-pixel, filling in nodata. That's something I should add to the description!
I was thinking about if it also needed to show facet plot over time of the inputs, but the other composites worked alright without it. It would be good to be able to generate a per-pixel age plot, to show the sources of the composite.
I think there are going to be quite a few notebooks to come out of the DEAfrica uplift that will need to get ported over to DEA.

**Comment by robbibt** [comment]
Awesome! Those kinds of compositions are potentially a super powerful technique, but might be a bit confusing for new users who aren't as familiar with multidimensional arrays. A per pixel age plot (maybe with age in days?) would be really nice, and would illustrate the concept really well I think!

There's an issue here to try and keep track of things to port back to DEA-notebooks, feel free to update it as you come across anything you think that should be on both repos! https://github.com/GeoscienceAustralia/dea-notebooks/issues/533

**Pull request merged**
