### PR TITLE
Floating Marine Debris

### PR DESCRIPTION
**Pull request by mpho-sadiki**
### Proposed changes
Draft notebooks for the floating microplastics use case. 
Includes notebooks that explore the data and one that applies the Floating Debris Index (FDI) to identify floating microplastics

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [x] Include relevant tags in the first notebook cell and re-use tags if possible
- [x] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Review by nanaboamah89 — APPROVED** [review]
Great Work @mpho-sadiki

**Review by mickwelli — COMMENTED** [review]
Very cool and comprehensive notebook with impressive results and explanations. 

A few questions:
•	Just before the import libraries cell there is a note about multiple timestamps. It is not immediately obvious what this refers to. Could this note be moved adjacent to the cell it relates to and maybe add some explanation as to how the timestamp(s) are defined in the code?
•	In the select location section, could some commentary about the NASA geojson file be added? E.g. explain that a supplementary location file is being loaded, what information it contains, and where it was sourced from. It would be good to introduce the NASA data at this point or early in the notebook.
•	I assume that the date `2018-10-31` relates to the NASA data? Could some text be added to explain this? As above, it would be good to introduce the NASA data earlier in the notebook before the accuracy assessment.
•	Is it possible to use DE Africa coastlines for masking rather than World Bank?
•	Is the distribution of the FDI values in the histogram expected? Could the range of the x-axis be reduced/number of bins in the histogram increased for better visualisation?

**Comment by mickwelli** [comment]
Thanks Mpho, looks good. I'm curious about the FDI distribution plot - clearly there are very few high value, but most values are 0 or close to. I suppose the spatial plot shows this (the high FDI values correspond to the plastics), whereas there is more variation in NDVI. Interesting!

**Review by mickwelli — APPROVED** [review]

**Review by lisarebelo — APPROVED** [review]
This a great notebook - well structured and well documented. A few minor changes:

In the second descriptive paragraph please change "global environmental concern" to "global priority"

Check formatting of Description section (remove space after each numbered item and place after last bullet)

Remove "*" from beginning and end of last para in Description section. Add this as a separate paragraph, normal text.

Correct typo in text following ln 11 ("Noramlised")

Correct text below ln 18 (normal text not bold)

**Pull request merged**
