### PR TITLE
Okavango use case

### PR DESCRIPTION
**Pull request by fangfy**
### Proposed changes
The Okavango use case is coming to a close so time to move the notebooks into the master branch. The notebooks demonstrate the use of WIT, maps the water-extent of the delta, models the delta's upstream discharge using rainfall data, and forecasts the water-extent using the modeled discharge.  The markdown in these notebooks is a little sparse but I think that's fine for use-case notebooks.

### Closes issues
- Closes Issue #216

### CODE REVIEW

**Comment by fangfy** [comment]
Hi @kmfundisi, started a notebook and tested water extent mapping for a small area in Okavango. Thoughts are welcome. Will continue to experiment with more land cover types.

**Comment by cbur24** [comment]
@fangfy can we migrate this notebook into its own folder in the `Use_cases/` directory? All the necessary data (shapefiles, results etc) can also be stored there, following the model of the [Lake Baringo](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/tree/master/Use_cases/Lake_baringo_grazing) use case

**Comment by mhalabisky** [comment]
@fangfy Just trying to get up to speed. Can you point me to the folder where the notebook is contained?

**Comment by cbur24** [comment]
@mhalabisky the notebook is [here](https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/tree/okavango/Use_cases/Okavango)

**Pull request merged**
