### PR TITLE
Radar phenology

### PR DESCRIPTION
**Pull request by cbur24**
### Proposed changes
- New radar phenology notebook
- Updates to optical phenology notebook
- Tweaks to `xr_phenology`, and `temporal_statistics`

### CODE REVIEW

**Comment by eefaye** [comment]
I ran pytest on this branch, there are a few issues - haven't had a chance to check up on them
```
Beginners_guide/02_Products_and_measurements.ipynb
Datasets/Soil_Moisture.ipynb
Frequently_used_code/Principal_component_analysis.ipynb
Real_world_examples/Change_filmstrips.ipynb
Real_world_examples/Radar_vegetation_phenology.ipynb
Real_world_examples/Vegetation_phenology.ipynb
```
I thought this PR says `Vegetation_phenology` got deleted, so I'm not sure why it's still showing up in the folder. 
Specific cells for `Radar phenology` was

```
FAILED Real_world_examples/Radar_vegetation_phenology.ipynb::Cell 15
FAILED Real_world_examples/Radar_vegetation_phenology.ipynb::Cell 16
FAILED Real_world_examples/Radar_vegetation_phenology.ipynb::Cell 17
FAILED Real_world_examples/Radar_vegetation_phenology.ipynb::Cell 19
```

`Principal_component_analysis` had 8 cells fail, I don't know if it's related to phenology but worth checking. If not, then we can open a separate PR to deal with it.

**Comment by cbur24** [comment]
`Vegetation_phenology` wasn't deleted, it was just moved to `Real_world_examples`. I fixed `Soil_moisture` this morning so changes just need to be merged into this branch. I'll look into the others, might be stuff related to sandbox images changes

**Comment by cbur24** [comment]
Oh `Radar_phenology` fails because you need to re-install `deafrica-tools` for it work since this PR involves changes to `deafrica-tools`

**Comment by eefaye** [comment]
Oh, classic. I forget that every time. I'll rerun the test for the notebooks that failed

**Comment by cbur24** [comment]
@eefaye sorted all the issues.
- PCA had a `load_ard` call that wasn't compatible with our recent changes to `load_ard`
- Products-and_measurments failed due to recent changes to the `dc.list_products()` method
- change filmstrips is working fine
- Merged changes to soil moisture so should be working fine now too.

**Comment by eefaye** [comment]
Alright, awesome. The only new failure for the proper pip installed pytest was:
```
Beginners_guide/05_Basic_analysis.ipynb
```
It's still running though. Will update this comment as and when it finishes

**Comment by cbur24** [comment]
I'll troubleshoot any more issues that pop up. FYI `Basic_analysis` runs fine for me so not sure what's happening there

**Comment by eefaye** [comment]
Lake Baringo looks like it's having problems now:
```
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb
```

**Comment by nanaboamah89** [comment]
Hi @cbur24, I will review the notebook tomorrow my day and provide feedback on it. @eefaye I will be happy to know how you use the pytest on the branch.

**Comment by cbur24** [comment]
@eefaye I think we're all good now

**Comment by eefaye** [comment]
Hey @nanaboamah89 , you can run Pytest from Terminal and the instructions are here: https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/wiki/Test-changes-on-the-Sandbox-Notebook-repository-with-Pytest 
Unlike me, don't forget to uninstall and re-install `deafrica-tools` first
The current pytest command I use is `pytest --nbval-lax . --ignore=Tools/` 
This tests almost the whole repository so it can take forever - I wouldn't recommend it if you are busy or want to use the Sandbox for other things.

If you want to run it on just the Lake Baringo files,  `pytest --nbval-lax Use_cases/Lake_baringo_grazing/` or something like that should work. It would be helpful to retest those as Chad updated them.

Let me know if you have any questions!

**Comment by nanaboamah89** [comment]
@eefaye thank you for the guideliness, I will go through today and if i have any questions I will alert you.

**Comment by nanaboamah89** [comment]
Hi @cbur24, find below an error encoutered at the phenology function, is in relation to the VERBOSE, but if removed, it was able to execute.
Screenshot 2021-09-14 at 11 42 36

Is it possible to also ignore warning such as below by not showing it?
Screenshot 2021-09-14 at 11 50 34

@eefaye I run the python test and it's a cool tool, it also pinpoints the error as shown below:
Screenshot 2021-09-14 at 11 43 02
Screenshot 2021-09-14 at 11 42 36

Quick Question: I noticed the pytest can run on a notebook of interest without going through all the files in the folder.  Is it advisable to do that or one should go through all the files in the folder?

**Review by eefaye — APPROVED** [review]

**Comment by eefaye** [comment]
@nanaboamah89 I'm not actually sure the benefit of running pytest on a single file as opposed to just running the notebook. I suppose it summarises the results for you without you having to go through the notebook. Sometimes, pytest will give failures where there aren't any though.

**Pull request merged**
