### PR TITLE
Update phenology functions to work across calendar years

### PR DESCRIPTION
**Pull request by vikineema**
### Proposed changes
- Update `deafrica_tools.temporal` module functions to output dates ( `datetime64`)  instead of Day of Year (DOY)
-  Set `vsos` and  `veos` to NaN if an error occurs when calculating the statistics using `_vsos` and `_veos`
- Set original all-NaN pixels back to NaN in the `xr_phenology` and `temporal_statistics` . Therefore, the phenology statistics in the optical and radar notebooks do not need to be masked again using the crop mask.
- Fill NaNs using the nearest interpolation method when calculating the zonal phenology statistics
- Update plotting in the optical and radar phenology notebooks to plot dates as float values.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [x] Include relevant tags in the first notebook cell and re-use tags if possible
- [x] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Comment by mickwelli** [comment]
Thanks @vikineema, I am getting errors in both the optical and radar notebooks as below (executed cell 20). I am guessing because the outputs for EOS and SOS are now DOY rather than datetime. We can either:

1. Plot the results with DOY as the variable 
2. Convert from DOY to datetime

What do you think?

`'.dt' accessor only available for DataArray with datetime64 timedelta64 dtype or for arrays containing cftime datetime objects.`

**Comment by vikineema** [comment]
> Thanks @vikineema, I am getting errors in both the optical and radar notebooks as below (executed cell 20). I am guessing because the outputs for EOS and SOS are now DOY rather than datetime. We can either:
> 
> 1. Plot the results with DOY as the variable
> 2. Convert from DOY to datetime
> 
> What do you think?
> 
> `'.dt' accessor only available for DataArray with datetime64 timedelta64 dtype or for arrays containing cftime datetime objects.`

The outputs of EOS and SOS are now datetime , previously they were DOY. 
image. 

When plotting,  the datetime values are converted into floats. 
image

**Comment by mickwelli** [comment]
Thanks @nanaboamah89. It looks like there is still a problem with the SoS, PoS & EoS plots; they have no spatial variation i.e. every pixel has the same value. They should reflect the cropland presence as in this image. 
image

**Comment by nanaboamah89** [comment]
@mickwelli that's true, thanks for the feedback. I will investigate further.

**Comment by mickwelli** [comment]
Thanks @nanaboamah89 the phenology charts for EOS and SOS look good now. The `temporal_statistics` function in the optical notebook is producing NaN values for discordance. Could you please investigate whether this is expected?

**Comment by nanaboamah89** [comment]
Hi @mickwelli I check the discordance values, and it keeps generating nan values for all the areas I tested. I also checked the old notebook, and the discordance was generating nan values too.

**Review by lisarebelo — APPROVED** [review]
This looks great, thanks for the changes.

**Pull request merged**
