### PR TITLE
WSF evolution notebook

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes
Created the World Settlement footprint evolution dataset.

### Checklist (replace `[ ]` with `[x]` to check off)
- [ ] Remove any unused Python packages from `Load packages`
- [ ] Remove any unused/empty code cells
- [ ] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [ ] Include relevant tags in the first notebook cell and re-use tags if possible
- [ ] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Review by mickwelli — CHANGES_REQUESTED** [review]
Nice notebook, I especially like the plots and animations.

A few things to consider:
1. The product is variously referred to as WSF-Evolution or WSF evolution. It would be good to make this consistent.
2. I can see an area on the Nile Delta is chosen. I think this is a good example. It would be good if there was some text that gave commentary on what is observable from the plots/animations for this specific location, and if the location was introduced in the text early in the notebook.
3. There is some repeated text in the Background and Spatial Plotting of WSF-Evolution data sections. It would be good if the later section could be re-worded to avoid repetition.
4. Are there more details for the G.D. Team reference? I assume this is Global Development Team or similar? The link doesn't provide much info. If no further details are available I think this reference can be omitted. The source publications are most important.

**Comment by mickwelli** [comment]
Thanks Edward, this notebook is looking good. A few questions:
•	Background section: “The IDC score is available on a yearly basis between 1985 and 2015” I don’t think this is true – I think it’s just one IDC score value for the entire period?
•	Analysis Parameters: ‘defining the color scheme for wfs 2015 and 2019 plotting’. I don’t think these are used in this notebook, so they can be deleted?
•	I suggest moving the ‘Calculate the area of settlement footprint’ section to just before the ‘Plotting of the WSF Evolution data’ section where it is implemented.
•	Is it possible to have the most recent year as the title of the animation so it changes as the animation progresses? Let me know if I can help.

**Comment by nanaboamah89** [comment]
> • Background section: “The IDC score is available on a yearly basis between 1985 and 2015” I don’t think this is true – I think it’s just one IDC score value for the entire period? The IDC score values change depending on the pixels.

**Review by mickwelli — APPROVED** [review]
Looking good!

**Review by lisarebelo — APPROVED** [review]
Thanks Edward, this is a good demonstration of the dataset.

**Pull request merged**
