### PR TITLE
Sentinel-1 for water detection

### PR DESCRIPTION
**Pull request by NMoghaddam**
### Proposed changes
Include a brief description of the changes being proposed, and why they are necessary.

### Closes issues (optional)
- Closes Issue #000
- Closes Issue #000

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell and re-use tags if possible
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Comment by NMoghaddam** [comment]
Thank you for reviewing this notebook and providing feedback.

**Review by fangfy — CHANGES_REQUESTED** [review]
* Spotted a few typos in the text descriptions
* if a fixed threshold is used for final classification, it is not necessary to use the auto-threshold detecting script. The way to use that function will be to plot the overall diagram and find the optimal minimum from the overall distribution
* I would just use WI for S2. TCW uses an arbitrary threshold that gives very different result.

**Comment by NMoghaddam** [comment]
All items raised by the reviewer except the last one addressed in the notebook. The last item needs more thinking about the approach in order to better compare two indices due to the spatial resolution differences.

**Comment by NMoghaddam** [comment]
@fangfy and @cbur24  I edited the notebook following a recent discussion yesterday and added a few contexts to the interpretation. Please check and advise.

**Comment by cbur24** [comment]
@neginmoghaddam @fangfy I've made a number of changes to the S1 water detection notebook.  I ported more of the plots from the earlier radar water detection notebook as I thought the workflow 'flowed' a little better using these plots.  I've also, somewhat opinionatedly, removed parts of the notebook that I thought weren't adding a lot of information but extended the length of the notebook. For example, the 'mean filter' segment, and the facet plots that weren't showing much.  The S1 values have also been converted to dB as this makes for much nice histogram plots.  

Also, maybe we should make a shoreline detection notebook using S1 now that we can match tide times with the S1 images?

**Comment by NMoghaddam** [comment]
Thanks, @cbur24 for the review and the proposed changes to the notebook. I am happy to keep the values in dB if it is something that @fangfy approves. We had a couple of discussion on not using the dB values. No doubt that the histogram plots are pretty now. On the side of the facet, my main objective was to show the backscatter signature in each polarisation for comparison- I added a few lines of interpretation about them but I can see that they were removed. 
I think S1 for shoreline detection could be a good case study if you have any suggestion on the location.

**Comment by fangfy** [comment]
converting to dB is good for thresholding, but we should apply lee filter first. And I think the threshold should be lower than -22 in this case? I suggest explicitly define threshold_vh because the threshold is very different for vv.

**Comment by fangfy** [comment]
Is the removed facet plot the one showing change over time? maybe that can be added towards the end as to discuss
* coastal and wetlands are highly dynamic, so cloud free assessment with radar is valuable to capture change in all seasons.
* this method doesn't work for water area with standing vegetation. this will result in difference when comparing to optically mapped extent

Also, should this notebook be in frequently used code instead of real world example?

**Comment by cbur24** [comment]
@fangfy my opinion is it should stay in `Real_world_Examples` as its quite an extensive notebook and covers more than just one or two analysis snippets.  The markdown at the top of the notebook also highlights a use case - water classification - which fits with the `Real_world_examples` theme.  I might be a good idea though to have a notebook in `Frequently_used_code` that shows loading S1 data, applying a lee filter, and converting to dB.  Oh, and should the lee filter function be put into the `deafrica-tools.spatial.py` script?

**Comment by cbur24** [comment]
@neginmoghaddam in the `Products used` section at the top of the notebook, there is a reference to S2 that should be removed

**Comment by NMoghaddam** [comment]
@fangfy and @cbur24 requested changes are now applied including:
- Adjusting the coordinates to the location that better represent wetland dynamics 
- Adding a few sentences for better interpretation of S1 TS
- Removing the reference link to S2
- Adding facet plots for each polarisation bands and ratio band using S1 DN values 
- Restructuring the notebook to reflect lee filtering step first followed by a step to convert DN values to dB values 
- Change the keyword threshold to threshold_vh and choose a lower value than -22 dB.
Please let me know should I missed anything.

**Comment by cbur24** [comment]
A couple of things I noticed:
1. Not sure you need to do the RGB facet plot (`ln[10]`), as it doesn't add much and you're calculating `vh/vv` but without an explanation of why that's useful (and then its not used anywhere else in the notebook).  Also, when doing RGB plots, don't be afraid to use `deafrica-tools.plotting.rgb()`, its has all the functionality you've replicated with the verbose plotting code currently in the notebook.
2. The subtitle `Visualise S1 in its two polarisation bands and RGB colour composite` is misleading because there isn't a RGB plot in this section.
3. With the histogram analysis, the markdown says you're going to show the impact of lee-filtering on the histograms, but then you only plot the `vh` and `vv` filtered histograms, not the unfiltered histograms. I recommend restoring the plots from the previous iteration of the notebook.
4. Might be worth explaining the conversion from DN to dB. How it works and why its useful.

**Comment by fangfy** [comment]
Made a few updates and will push once I can save the notebook....
Mainly:
* Updated text to be consistent throughout can have explanations for each step
* Cleaned up import section to only include used packages
* Updated rgb plotting - scaled by median and use rgb()
* Removed reference to explorer because data is available everywhere for Africa.

**Comment by NMoghaddam** [comment]
@fangfy the notebook is now ready to be merged to the repo. Thanks, @cbur24 and @fangfy for your valuable inputs.

**Review by fangfy — APPROVED** [review]

**Pull request merged**
