### PR TITLE
World Settlement Footprint Dataset

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes

Notebook created to load all WSF datasets.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x ] Remove any unused Python packages from `Load packages`
- [x ] Remove any unused/empty code cells
- [x ] Remove any guidance cells (e.g. `General advice`)
- [x ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [x ] Include relevant tags in the first notebook cell and re-use tags if possible
- [x ] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Review by mickwelli — CHANGES_REQUESTED** [review]
Well structured notebook with great visualisations. 

The markdown at the beginning of the notebook is quite good. The markdown throughout the plotting and calculation steps is missing some details. E.g. under ‘plotting of spatial change’ could some additional markdown be added explaining what is being calculated and how users can interpret the plot? Same with the evolution layer – what do the values in the evolution layer mean and how can users interpret them?

**Review by mickwelli — CHANGES_REQUESTED** [review]
Hi Edward, thanks for the updates for the markdown.

A couple of points related to calculating area:
1. Please note that I have updated the area calculations. Could you please check these? Previously these were summing the pixel values (which are either 255 or years) and were producing grossly overstated areas e.g. 80,000 sq. km. I've changed these to a count of non-zero pixels multiplied by the area per pixel.
2. There is a difference in area in 2015 between the wsf 2015 product and evolution product. I've added a possible explanation (derived from different sensors), could you please see if you can find any further information on this / check the calculations?

**Comment by nanaboamah89** [comment]
Evolution Dataset removed from the notebook

**Review by mickwelli — APPROVED** [review]
Looking good

**Review by lisarebelo — APPROVED** [review]
Thanks Edward, looks good.

**Review by lisarebelo — APPROVED** [review]

**Pull request merged**
