### PR TITLE
Rgb with rain animation

### PR DESCRIPTION
**Pull request by mickwelli**
### Proposed changes
Notebook demonstrating the generation of rgb animations alongside rainfall data.

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [X] Include relevant tags in the first notebook cell and re-use tags if possible
- [X] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Review by lisarebelo — CHANGES_REQUESTED** [review]
Under the Description and analysis parameters make it clear that the notebook uses the DE Africa continental service (Mean NDVI and Anomalies). To do this change:

> Bring in NDVI data.
To:
> Load DE Africa Mean NDVI and Anomalies product

Below ln 4 change:
> Bring in
To:
> load the Mean NDVI and anomalies product

**Comment by mickwelli** [comment]
@lisarebelo I think your comments relate to PR #444 which I've just updated in response. For this PR #445 I am specifically interested in feedback on the temporal interpolation component of the RGB image and how it is described in the markdown. Thanks!

**Review by lisarebelo — CHANGES_REQUESTED** [review]
Hi Michael,

Thanks for clarification - a couple of suggestions:
1. Under the background description you refer to rainfall as:
> possibly associated variable, such as rainfall
Technically rainfall is a forcing variable in this situation and very clearly associated with land surface state - for clarity I would suggest to rephrase as:
> a variable which contributes to the land surface state such as rainfall

2. Under description change:
> products to product
to:
> products, to produce

3.  Change:
> The platform enables us to integrate these datasets within a year of interest 
to:
> Through the DE Africa Sandbox we can integrate these datasets over a time period of interest

4. Interpolation description, change:
> We want to generate an animation representing a year
to:
> We want to generate an animation for a single calendar year

5. Finally, check the x and y definition changes for plot.imshow under the Sandbox upgrade

In terms of the rgb interpolation - as it is for demonstration purposes only, it serves the goal of showing changes in the landscape using uniform time steps for smoother visualization. The cumulative rainfall would make more sense for a hydrological year (rather than a calendar year) but for visualization/demonstration purposes this is fine.  Overall it is a nice notebook with various different analytics for users to experiment with.

**Comment by mickwelli** [comment]
Thanks @lisarebelo, I've made some edits to the text and checked images are projected with correct x & y dimensions

**Review by lisarebelo — APPROVED** [review]

**Pull request merged**
