### PR TITLE
added burned area mapping notebook and modis hotspots file

### PR DESCRIPTION
**Pull request by nikhil003**

### CODE REVIEW

**Comment by caitlinadams** [comment]
@nikhil003, thanks for contributing this during the ODC Hackathon! 

There are a number of updates I'd like to do to get this into the DE Africa Sandbox. Would you still like to work on this notebook and see the changes I make? Otherwise, I will close this PR and duplicate it as a branch on the DE Africa repo to avoid making direct changes to your fork. If you'd still like to contribute, I will make changes directly to your fork.

**Comment by nikhil003** [comment]
@caitlinadams, yes, I would be happy to work with you on this notebook to get it into the sandbox.

**Comment by caitlinadams** [comment]
Sorry if I've overwritten anything you've done! Would you like me to stop working on it now so that you can spend some time on it?

**Comment by nikhil003** [comment]
That's no problem, I will stop working on it as I was going to follow your suggested changes anyway.

**Comment by caitlinadams** [comment]
It would be great if you could add some markdown information around how you collected the MODIS data! I can go back to working on the other changes after you've done that.

**Comment by caitlinadams** [comment]
Thanks for adding your changes -- I was hoping to finish this up this afternoon. Have you got any more changes to push?

**Comment by nikhil003** [comment]
I have added stuff on how I got the hotspot information and why I used it. Also, I added some information on how to process the data. As I did the process offline so I did not get into too much detail. I don't have any more changes to push.

**Pull request merged**
