### PR TITLE
Illegal mining

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes
Include a brief description of the changes being proposed, and why they are necessary.

### Closes issues (optional)
- Closes Issue #000
- Closes Issue #000

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X ] Remove any guidance cells (e.g. `General advice`)
- [ X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [ X] Include relevant tags in the final notebook cell and re-use tags if possible
- [ X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Review by eefaye — CHANGES_REQUESTED** [review]
Hi @nanaboamah89 , the results of the notebooks are great. I just wanted to confirm a few things:

- Which copy of the notebook is the one you want to push to the repo?
I assumed it was `ld_wd.ipynb` and did some minor edits in there, but there is still a notebook called `Illegal mining` and there are a whole bunch from `Brian_...` etc. 
Before the branch can be merged, these probably need to be moved.

- In `ld_wd` the `baseline_year`, `analysis_year` variables were not used, please delete them

**Comment by nanaboamah89** [comment]
Hi @eefaye, Thanks for the update. 
Which copy of the notebook is the one you want to push to the repo? ld_wd.ipynb
Illegal mining, Brian_... etc have been removed from the branch

In ld_wd the baseline_year, analysis_year variables were not used, please delete them. they have been removed.

**Review by eefaye — CHANGES_REQUESTED** [review]
Thanks Edward! I noticed you have changed the area of interest and it really shows the change in vegetation/water.

Only a few things:

 - Notebook title: I have noticed we already have notebooks about water extent and vegetation change. I'd like to suggest we call this notebook 'Land degradation'. You are welcome to change the title if you prefer something else.

 - WOfS and MNDWI section: The WOfS section looks great! I would like to suggest that you remove the MNDWI sections. I think it looks good but it detracts from the WOfS part. If you have a reason for leaving it in, it might be helpful to explain which is better or why they show different results. 
For MNDWI to give a meaningful result, it needs to be thresholded to separate "water" and "not-water". Without a threshold, the `analysis-baseline` difference will just show any change in MNDWI regardless of whether it switched from water to not-water or vice versa. In your 4-plot subplot at the bottom, it actually looks like MNDWI is detecting the vegetation loss next to the river. This is confusing to have with the vegetation loss plot.

However, I think the WOfS part is more than sufficient to show the loss of water along the river. So we should remove MNDWI. 

 - The folder `Supplementary_data/Mining` should be cleared except for files which are used in the analysis. Is the area still "Northern Tindiret Forest Reserve"? The file path leads to `Apam_forest.shp`. If they are referring to the same place, it might be worth renaming the `.shp` file to reflect the location.

 - If the notebook is not being called 'Illegal mining' any more, then the `Supplementary_data/Mining` folder should be renamed to `Supplementary_data/Land_degradation` or whatever the final title is.

 - Is the `DCAL_Cloud Statistics` notebook supposed to be in this PR as well? It's not part of the master branch. I have not reviewed it; if it is also a new use case it might be better off in its own PR.

Thank you for the neat and clear code and comments. Hope this feedback is useful.

**Comment by nanaboamah89** [comment]
Thanks @eefaye !


Notebook title: I have noticed we already have notebooks about water extent and vegetation change. I'd like to suggest we call this notebook 'Land degradation'. You are welcome to change the title if you prefer something else.
**The Land degradation name is good**

WOfS and MNDWI section: The WOfS section looks great! I would like to suggest that you remove the MNDWI sections. I think it looks good but it detracts from the WOfS part. If you have a reason for leaving it in, it might be helpful to explain which is better or why they show different results.
For MNDWI to give a meaningful result, it needs to be thresholded to separate "water" and "not-water". Without a threshold, the analysis-baseline difference will just show any change in MNDWI regardless of whether it switched from water to not-water or vice versa. **Threshold is set**
In your 4-plot subplot at the bottom, it actually looks like MNDWI is detecting the vegetation loss next to the river. This is confusing to have with the vegetation loss plot. **The 4 plots have been reoved**

However, I think the WOfS part is more than sufficient to show the loss of water along the river. So we should remove MNDWI. **MNDWI was used for area where WOFS did not detect water**

The folder Supplementary_data/Mining should be cleared except for files which are used in the analysis. Is the area still "Northern Tindiret Forest Reserve"? The file path leads to Apam_forest.shp. If they are referring to the same place, it might be worth renaming the .shp file to reflect the location.

If the notebook is not being called 'Illegal mining' any more, then the Supplementary_data/Mining folder should be renamed to Supplementary_data/Land_degradation or whatever the final title is. **Changed**

Is the DCAL_Cloud Statistics notebook supposed to be in this PR as well? It's not part of the master branch. I have not reviewed it; if it is also a new use case it might be better off in its own PR. **Removed**

**Comment by caitlinadams** [comment]
Hi @nanaboamah89,

Thank you for your work on this. The main change that needs to happen is the selection of area where known legal mining is occurring. From there, the text can be updated to better describe the use case and analysis. In the meantime, here are some smaller suggestions:

- For the "Calculate the anomaly in vegetation" section, it would be great if you could add some text to explain the steps here. For example, why is the threshold 0.2? I would also rename your variables and values to be better suited to the example. I would remove the "sig_" from each parameter (since you're not actually testing for statistical significance), and set the "name" values as "Vegetation Loss" and "Vegetation Gain" respectively; this way you're not implying that it's always loss/gain of forest cover.
- Similar to above, change the title on the fourth plot to reflect vegetation loss, rather than deforestation.
- I think it would be best to only use one water analysis in the main notebook; probably WOfS since it's undergoing validation. For the MNDWI analysis, perhaps you could add some suggestions to the user about how they might change the analysis to use MNDWI instead. This will clear up the notebook, but give people enough information if they want to try a different measure of water. 
- In your change plots, you have the following categories:
    - vegetation loss
    - water to water
    - water to no water
    - no water to water
for clarity, I would suggest changing these to:
    - vegetation disappeared
    - water remained
    - water disappeared
    - water appeared 
or something else that uses easy and consistent language.

**Review by caitlinadams — CHANGES_REQUESTED** [review]
See above comments

**Comment by eefaye** [comment]
Hi Edward, 

The notebook looks good, it's undergone lots of changes from when I last saw it! I think it's a lot more streamlined now.

 - Before Cell [8], it would be good to have a short explanation for each of NDVI, MNDWI, and WI. 

 - Do we end up using the afforestation variable?
`# Determine areas with significant afforestations (positive difference)`
`vegetation_gain = parameter_anomaly > 0.2`
`vegetation_gain['name'] = "Vegetation_gain"`
If not, we should probably get rid of those lines.

 - Cells [20] and [21] require a bit more explanation as to what is happening in them - it's not the same as the WOfS section.

 - Cell [21] says `# A threshold greater than 0 is  for area where MNDWI indices is water`
`threshold_value = 1.720`
Firstly, that cell refers to the WI calculation. Secondly, how did you obtain a threshold value of 1.720?

 - I think the vegetation loss section is very clear. I have added some description to the Water section, but it would be good if you could review it. The Water section is more complicated because it uses multiple indices, so we should provide more explanation to what is happening. 

 - We should be avoiding the phrase 'Land degradation' as it overlaps with the sustainable development goals. It would perhaps be good to call this notebook `Potential_mining_areas`, `Mining_detetction` or something similar. What do you think?

 - (Suggestion) After Cell [23] you could add a markdown cell subtitled "Next steps" and indicate that these potential areas can be crosschecked or investigated by authorities

 - (Just a thought - we can discuss this further) What if we made the notebook narrative focus more on mining instead of illegal mining? It seemed that was a point of contention earlier, but it would be simple to focus this notebook around just **mining**. Then we can, as an aside, mention the identified potential mining sites can be compared with registered sites.

**Comment by cbur24** [comment]
@caitlinadams Do you know what's happening with this notebook? Are we planning on adding a version of the illegal mining notebook into the repo?

**Pull request closed without merging**
