### PR TITLE
Add SDG notebook

### PR DESCRIPTION
**Pull request by vikineema**
### Proposed changes
Add SDGs notebook that links to all existing notebooks useful for SDGs, grouped under each SDG indicator.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [x] Include relevant tags in the first notebook cell and re-use tags if possible
- [x] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Comment by gumpgourou** [comment]
It looks really good!

1. I assume that when finished the links will point to notebooks within the sandbox? 
2. I would be keen to explore the ideas to:

- duplicate and export the page as HTML to put on our website, Docs, Community on Helpdesk with links pointing to Docs notebooks, as opposed to links within the 
- create slides per thematic areas for awareness-raising, workshop hands-out etc...
- probably other ideas will pop up.

Also, I would also put the Coastline notebook into SDG 13
Thank you and great job!

**Review by nanaboamah89 — COMMENTED** [review]
@vikineema Great work,

**Review by mickwelli — APPROVED** [review]
Looks great! What do you think about including links to datasets nbs? E.g https://docs.digitalearthafrica.org/en/latest/sandbox/notebooks/Datasets/Landcover_Classification.html landcover datasets nb has some relevance to monitoring cities and forest change. I am not sure...

**Comment by fangfy** [comment]
> 

I agree that some of the datasets have direct links to SDG. I think we should add Datasets notebooks that are either our services (cropland extent, wofs, fractional cover) or land cover - so all the high level information products.

I've also tweaked the title and text to make it a bit broader and directly mention the DEAfrica services as part of it.

**Comment by fangfy** [comment]
One more comment: there are three files in the folder, I assume this is to make sure the links work in both sandbox and docs. Can we make it more explicit then which one should be used where - in the title, in the description or a README in the folder.

**Comment by fangfy** [comment]
one more, 15.4.2 is missing?

**Review by nanaboamah89 — APPROVED** [review]
The current stage is fine to merge it to the notebooks.

**Review by fangfy — APPROVED** [review]

**Pull request merged**
