### PR TITLE
Add interactive ML notebook

### PR DESCRIPTION
**Pull request by Gabzgit**
### Proposed changes
Add an interactive ML notebook.
Edit deafrica_classificationtools so that a geopandas dataframe is required rather than the path.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell and re-use tags if possible
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Comment by cbur24** [comment]
I'm getting `permission denied` errors whenver I try to push to your fork @Gabzgit, can you please check that 'maintainers' have access to write to the PR?  Its possible I'm doing something wrong from my end also.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Gabzgit** [comment]
> I'm getting `permission denied` errors whenver I try to push to your fork @Gabzgit, can you please check that 'maintainers' have access to write to the PR? Its possible I'm doing something wrong from my end also.
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

"Allows edits from maintainers" is checked.

**Comment by robbibt** [comment]
@s-m-t-c We should at some point update the classification script to use the faster version of the training data function we hacked together a few weeks back (both here and on DEA-notebooks)

**Comment by cbur24** [comment]
> We should at some point update the classification script to use the faster version 

I'm also making some pretty major updates to the `deafrica_classification.py` script, so we may want to review them for DEA once I'm done too

**Pull request closed without merging**
