### PR TITLE
Phenology notebook

### PR DESCRIPTION
**Pull request by caitlinadams**
### Proposed changes
Uplift of the DCAL Phenology notebook, with some code simplification and additional markdown explanation at all stages.

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell and re-use tags if possible
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Comment by cbur24** [comment]
@caitlinadams @andrewdhicks The notebook and script are in a pretty good state now and could do with a fresh review if either of you have time.

**Comment by andrewdhicks** [comment]
I'll have a look at it this afternoon @cbur24 
Xarray has also just released their latest version, so I'll look at updating the `nearest` etc functions so they are dask-enabled.

**Comment by cbur24** [comment]
Thanks @andrewdhicks.  For the `xr_phenology` function I removed the dependency on `first` and `last` (used a neat little work-around with `.median()`), but if you could also look at other aspects of that function that could be daskified (even just one example that I could build off) then that'd be greatly appreciated.  In my testing I've found the function to be very fast, but also very memory hungry. Scaling could be difficult if we can't enable dask.

**Comment by andrewdhicks** [comment]
Hi @cbur24, the notebook looks really good and the `xr_phenology` function makes it nice and clear!

- [ ] Move to `Real_world_examples` folder?
- [ ] Add a Conclusions section, maybe pointing out what we have learnt from the various per-pixel plots?
- [ ] Next steps: If there are any relevant advanced notebooks, or we can just describe how to go back and change the area or vegetation index?

Minor code and formatting issues:
- [ ] in the Description section, NDVI and EVI are formatted as code/monospaced. Maybe bold instead?
- [ ] remove `warnings` filters - we are moving to fixing issues in our scripts, and explaining actual relevant user warnings in the notebook
- [ ] remove `autoreload` once you have finished doing the dev work on 
- [ ] add `;` to the end of the line `ndvi.mean(['x','y']).plot.line('b-^', figsize=(11,4))`
- [ ] Per-pixel phenology statistics: to fix the aspect ratio of the plots, try:
   ```
   fig, ax = plt.subplots(nrows=5, ncols=2, figsize=(18,15), sharex=True, sharey=True)

   for a in fig.axes:
       a.set_aspect('equal')
   ```

Also, a quick question: I've only ever seen "zonal" stats being referred to when there is a zone classification raster involved. Is it just term for aggregating over area, and in this case we just have a single zone?

I'll let you know how I go with the dask-ifying.

**Comment by cbur24** [comment]
@andrewdhicks thank you for the comprehensive review. I've addressed/incorporated all but one of your suggestions.  I was thinking it might make more sense to leave this notebook in the `Frequently_used_code` section because we aren't really addressing a specific environmental management problem, but rather simply demonstrating a capability.  If one of our users comes up with a specific use-case then lets write a separate notebook for that.

And yeah, I use the word 'zonal' as a general term to mean 'spatial mean', I think I picked it up in a remote sensing class somewhere.

**Comment by andrewdhicks** [comment]
I've added the dask functionality, but it requires xarray v0.16.0.

There's a few things that I'm not sure about:

- I'm using `HiddenPrint` to hide the output for each chunk being processed. We should look at switching over to a more configurable logging method at some point.
- I'm using `dask`'s `persist()` method to save interim results to the dask cluster, which won't scale.
- I has to remove the per-pixel `time` coord being returned from `xr_phenology`, but I'm not sure what time it held.

**Comment by andrewdhicks** [comment]
Converted to **Draft** until sandbox gets upgraded to `xarray>=0.16.0`

**Review by fangfy — APPROVED** [review]
The notebook looks good to me and I'm happy for it to be merged. One minor comment is that it's not clear what's the difference between the various smoothing and gap filling options and whether there's a "recommended default" that a user should use.

**Pull request merged**
