### PR TITLE
Burnt area mapping near real-time

### PR DESCRIPTION
**Pull request by mpho-sadiki**
### Proposed changes
New Near real-time burnt area mapping notebook from DEA (https://knowledge.dea.ga.gov.au/notebooks/Real_world_examples/Burnt_area_mapping_near_realtime/) 

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Remove any unused Python packages from `Load packages`
- [X]  Remove any unused/empty code cells
- [X]  Remove any guidance cells (e.g. `General advice`)
- [X]  Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [X]  Include relevant tags in the first notebook cell and re-use tags if possible
- [X]  Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [X]  Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Review by mickwelli — CHANGES_REQUESTED** [review]
Nice workflow and the default area & time is great!

- Suspect that `EPSG:6399` (Alaska) is meant to be `EPSG:6933`, I've committed and pushed this change
- The `plot_variable_images()` function: I think there are 2 options. 1) Add the function to the `deafrica_tools.plotting` module or 2) Add an explanation prior to defining the function.
- Near RT Image Selection: could an explanation be included as to why image 3 was selected in the example case e.g. cloud free and Sentinel; therefore higher resolution than Landsat? Same for baseline image selection

**Comment by mpho-sadiki** [comment]
>Thanks Michael. I have added some markdown for the function and the NRT and baseline image selection.

**Review by mickwelli — APPROVED** [review]
Thanks Mpho

**Review by lisarebelo — APPROVED** [review]
Thank you Mpho, great to have this notebook available. It is well described with a really nice example and useful optional extras.

A couple of minor edits:
- remove capitalization in the section titles below (and any others, except for satellite names):
>Define suitable date ranges for the baseline and Near Real-time Images
>Load, Visualise, and Select a Near Real-time image
In this section, edit "change of finding a suitable image" to "chance of finding a suitable image"

**Comment by mpho-sadiki** [comment]
> Thank you Mpho, great to have this notebook available. It is well described with a really nice example and useful optional extras.
> 
> A couple of minor edits:
> 
> * remove capitalization in the section titles below (and any others, except for satellite names):
> 
> > Define suitable date ranges for the baseline and Near Real-time Images
> > Load, Visualise, and Select a Near Real-time image
> > In this section, edit "change of finding a suitable image" to "chance of finding a suitable image"

Thanks Lisa.

**Pull request merged**
