### PR TITLE
Parallel training data collection

### PR DESCRIPTION
**Pull request by cbur24**
### Proposed changes
Previously `deafrica_classificationtools.py` used the function `get_training_data_for_shp` to extract training data from a shapefile by sequentially looping through each geometry.  While this approach was fine for relatively small numbers of geometries (< 100), this approach becomes prohibitevly slow once the number of geometries greatly increases and/or you attempt to load a long(ish) timeseries of data for each geometry.  This PR updates `deafrica_classificationtools.py` to include several new functions that allow for loading and processing training data in parallel across a specified number of cpus:

- `collect_training_data`: this is the function that is called in the notebook. It executes the training data functions and tidies the results into a 'model_input' object containing stacked training data arrays with all NaNs removed.
- `get_training_data_parallel` : This function is called if `collect_training_data` is passed with ncpus > 1. It sets-up and runs the `get_training_data_for_shp` function in parallel by sending the function and  geometries to a `multiprocessing.pool()`
- `get_training_data_for_shp` has been simplified and now includes the ability to accept a custom function for generating feature layers. It has also been altered to remove the embedded for loop to allow for multiprocessing.

Timing the serial vs parallel versions on the high CPU sandbox environment (15 CPUs according to `env | grep CPU`) reduced the time to load 12 months of LS8 data from 80 polygons from 1.5 hours to ~9 mins.

The notebook `Machine_learning_with_ODC.ipynb` has also been updated to reflect the changes in the training data functions (as these are breaking changes).

### CODE REVIEW

**Comment by cbur24** [comment]
Thanks for the review @fangfy. 
1. I removed that section, as it's redundant in this example as you said
2. I'm not 100% sure how to deal with the `Prediction` section because if the user alters any of the default settings then the `Prediction` section needs to be updated - and I don't wish to have a long series of `if-else` statements in the notebook catching every iteration. For now, I've added a note in the markdown of both the `Analysis Parameters` and `Prediction` sections highlighting that the user needs to update the Prediction section manually if they change the default settings.
3. I don't receive any errors when I run the `feature_importance` section on the notebook so will leave that as-is for now.   

I believe @s-m-t-c will conduct a review soon so will not merge until his review is complete.

**Comment by fangfy** [comment]
#2: band_indices is the main difference that will change the number of features used. And it's relatively straightforward addition if you make the default an empty list. I think most of the other things are OK left as is, e.g. if you train using zonal stats, you can still apply on the geomedian image. It is a good idea adding a note.
#3: doesn't throw you an error but it's actually wrong as not doing what's it supposed to be. I'd also sort in reverse order, from most important, but that's not critical.
I'll leave it to @s-m-t-c to fix then :)

**Comment by cbur24** [comment]
- I see what you mean now with the feature importance order, I've implemented your suggestion.
- Also added band indices as an option in the prediction section, but left the variable empty in the default settings as the model does a better job of classifying without band indices.

**Comment by fangfy** [comment]
Sounds good. Happy for you to merge whenever.

**Comment by s-m-t-c** [comment]
Nice work here, I've made some small changes and gave most of the function options a solid test. I'll note that some of them do not work simply due to limited data availability and the training dataset itself.

**Comment by cbur24** [comment]
Thanks for the very thorough and throughful reviews @fangfy @s-m-t-c!

**Pull request merged**
