### PR TITLE
Planet basemap

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes
Notebook for visualizing the Planet monthly mosaic data.

### Checklist (replace `[ ]` with `[x]` to check off)
- [ X] Remove any unused Python packages from `Load packages`
- [X ] Remove any unused/empty code cells
- [X ] Remove any guidance cells (e.g. `General advice`)
- [X ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [X ] Include relevant tags in the first notebook cell and re-use tags if possible
- [X ] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [X ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Comment by nanaboamah89** [comment]
I used Sentinel-2 rolling geomad, with the most recent being September 2023. However, I selected a high-quality image(May 2023). However, when the latest image is available, the code will only use the most recent image, which corresponds to the planet's year and month. I added the current date for the rolling geomad to the attribution of the map.

**Review by fangfy — APPROVED** [review]
Looks good overall. Check the BUI and NDVI threshold used.

**Review by mpho-sadiki — APPROVED** [review]
Looks good, Edward.

**Comment by fangfy** [comment]
@nanaboamah89 you might want to try NDVI>0.6 to capture more vegetation. The BUI also miss some urban area, perhaps add some explanation that for optimal results, these thresholds should be tuned.

**Review by fangfy — APPROVED** [review]

**Review by mickwelli — CHANGES_REQUESTED** [review]
Great visualisation @nanaboamah89! Should planetbasemap.py be in the Datasets folder or be incorporated into deafrica-tools? Incorporation into Tools would be my preference as we don't have any other .py files in the Datasets folder.

**Comment by nanaboamah89** [comment]
> Great visualisation @nanaboamah89! Should planetbasemap.py be in the Datasets folder or be incorporated into deafrica-tools? Incorporation into Tools would be my preference as we don't have any other .py files in the Datasets folder.

Yes @mickwelli , it would be incorporated as part of the deafrica-tools before merging to the main.

**Review by lisarebelo — APPROVED** [review]
Looks great, thank you Edward. Two minor edits:

Background section:
Can you remove the capitals from "Visual and Analytic"

Description section:
Spell out NDVI and BUI as is first use

**Review by mickwelli — APPROVED** [review]

**Pull request merged**
