### PR TITLE
ERA5 climate data

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes
Notebook Repository is not able to load the ERA5 climate data. Trying to find alternatives to work with it.

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [x] Include relevant tags in the first notebook cell and re-use tags if possible
- [x] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Comment by mickwelli** [comment]
Thanks @nanaboamah89, could we have a notice at the top of the notebook saying something like: Tthis dataset is currently not supported as of January 2024, the DE Africa team are working on resolving the issue. For any enquiries please refer to the [helpdesk](https://helpdesk.digitalearthafrica.org/portal/en/home).

**Review by mickwelli — COMMENTED** [review]
@nanaboamah89 I've pushed a few changes. A few things to note:

1. I've added a new function `load_era5_g_2()` in the `load_era5_google` testing notebook. This function draws on analysis ready `ar` bucket rather than cloud-optimised `co`. Analysis-ready doesn't need re-gridding like the cloud-optimised data so it's a bit cleaner to load. I think it is preferred. Details on [google access site](https://cloud.google.com/storage/docs/public-datasets/era5). However, there are two issues I can see already:

a) We would need to update the link when it updates to include data beyond 2022.
b) The variables are slightly different to the original `load_era5()` but I think all the most used/important ones are included. More details in notebook.

2. I've updated the original `load_era5_g()` function to better accommodate precipitation from the forecast link. However, I think accumulated precip in the analysis-ready data (as above) is preferable to the forecast bucket.

Interested in your thoughts and sorry I didn't notice the `ar` bucket earlier!

**Comment by nanaboamah89** [comment]
@mickwelli `eastward_wind_at_10_metres` is giving NA values.

**Comment by mickwelli** [comment]
@nanaboamah89 I expect that the `ar` data will be updated beyond 2022

**Comment by mickwelli** [comment]
@nanaboamah89 this is awesome!

I've made a few changes:

1. Removed duplicate cells in the ERA5 datasets notebook.
2. Removed unsupported variables in the markdown table in the notebook, and in the dictionaries of the `load_era5` function.
3. Remove `reduce_func` and `resample` arguments in precipitation example as 24hr precipitation variable means they are no longer required.

Could you please check over/test these changes?

**Comment by nanaboamah89** [comment]
Thank you, @mickwelli. I tested the function on the other notebooks that relied on the era5 function, and they all now work.  I included the notebooks in the branch.

**Review by mpho-sadiki — APPROVED** [review]
All the notebooks work well. I just had to install **gcsfs** to access Google Storage. Well done @nanaboamah89!

**Comment by nanaboamah89** [comment]
@mpho-sadiki thank for drawing attention to the gcsfs. I would add it to the pyproject.toml.

**Review by mickwelli — APPROVED** [review]
Nice one @nanaboamah89

**Review by lisarebelo — APPROVED** [review]
Thanks for the update, look good.

**Pull request merged**
