### PR TITLE
S2 updates

### PR DESCRIPTION
**Pull request by cbur24**
### Proposed changes
Updating `deafrica_datahandling/load_ard` and `deafrica_bandindices` to work with the shiny new S2 data.  Corresponding notebooks have also been updated to reflect the changes.

### CODE REVIEW

**Comment by cbur24** [comment]
@NMoghaddam 
- I've now remapped the `B01`, `B02` etc band names to match their aliases `blue`, `green` etc inside the `band_indices` function.  This should handle the case where a user loads data without specifying measurements.

- Your RGB problem has to do with not specifying the `bands=[]` to RGB when trying to plot

- I can't replicate the issue with 'SCL', as the notebook works for me.

**Comment by fangfy** [comment]
I'm getting an error when trying to load SCL through load_ard(... measurements=['red','green','blue', 'SCL']). Not sure why though...

**Comment by cbur24** [comment]
@fangfy this is possibly because `load_ard` dumps the pixel-quality band by default after its done the masking. I will have a look at this again tomorrow.

**Comment by cbur24** [comment]
@fangfy This issue has been resolved now, turns out there was an errant line near the end of the function that shouldn't have been there  - the 'data bands' were re-assigned by mistake and thus removed any pq bands.

**Comment by fangfy** [comment]
@cbur24 @NMoghaddam the band used are in the script but I think it will indeed be very useful if we can update the notebook with a table, that lists index name, band1 and band2 (with a header explaining index is (band1-band2)/(band1+band2)

**Pull request merged**
