### PR TITLE
Scalable ML on the ODC

### PR DESCRIPTION
**Pull request by cbur24**
### Proposed changes
A notebook series exploring machine learning on the ODC. Includes a new  module called `deafrica_segmentation.py` which allows for parallel, tiled image segmentation. This part is not critical to the notebooks so please assess if its worthwhile adding

### Checklist (replace `[ ]` with `[x]` to check off)
- [X] Remove any unused Python packages from `Load packages`
- [X] Remove any unused/empty code cells
- [X] Remove any guidance cells (e.g. `General advice`)
- [X] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [X] Include relevant tags in the final notebook cell and re-use tags if possible
- [X] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Review by eloise-b — COMMENTED** [review]
These notebooks were really informative, and as a beginner to ML I found them to be accessible and easy to follow and learn from!

**Review by eefaye — APPROVED** [review]
1_Extract_training_data
 - Make it clear in the markdown that we are overwriting the original `column_names, model_input` and replacing it with the run using the `custom_func`, and that the only difference in them is the addition of the slope dem (and LAI, but could have done that in the original call right? Only the slope couldn't be input without the custom func) 

4_Classify_satellite_data
 - "then you can simply copy-and-paste your `custom_training_data` function from the first notebook" - I believe you have already copy and pasted the code from the first notebook? Unclear whether reader is supposed to take action - by my interpretation you have already done it and if they are using default settings there is no c+p to be done.

General comment:
It might be good to emphasise the base level of knowledge required to understand these notebooks. They are very readable and accessible, but do require familiarity with machine learning/statistical concepts, Earth observations knowledge, and comfortableness working with Python as at least an intermediate beginner.
Stating this clearly will avoid disappointment by users and/or the author receiving a bunch of out-of-scope questions that are covered by intro-level Sandbox material.
This could be done by adding conditions/pre-req/recommendations to the readme files - I know links to other resources are already there, but it might be worth linking the Beginner's guide and (perhaps) Machine_learning_in_the_ODC as strongly suggested pre-reading. 

Overall a really thorough deconstruction of a (somewhat) conceptually simple but fairly involved analysis process. I have no doubt it will be an incredibly popular and useful resource.

**Comment by fangfy** [comment]
It might be good to refer to the geojson as "labels" or "labeled data" instead of "training data" to distinguish it from training data with label and features.

**Comment by fangfy** [comment]
'results/classifications/' folder is not there, so saving prediction result failed.

**Review by fangfy — APPROVED** [review]
see my other minor comments, especially the filepath issue. Also noting that the gm is not official yet and we'll be moving/indexing slope but happy for informed users to try these.

**Comment by cbur24** [comment]
Thank you for the review @eefaye @fangfy @eloise-b!
I will address the comments relating to the the code and markdown.  As the for two readme's @fangfy, my thinking behind this is I wanted there to be a well rendered readme on both github (readme.md), and a readme on the sandbox (readme.ipynb) - `.md` files don't render on the sandbox.

**Pull request merged**
