### PR TITLE
Abalak burnt area Use Case

### PR DESCRIPTION
**Pull request by vikineema**
### Proposed changes
Add the Burnt Area Mapping Use case for for Abalak, Niger. 

### Closes issues (optional)
- Closes Issue #000
- Closes Issue #000

### Checklist (replace `[ ]` with `[x]` to check off)
- [x] Remove any unused Python packages from `Load packages`
- [x] Remove any unused/empty code cells
- [x] Remove any guidance cells (e.g. `General advice`)
- [x] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
- [x] Include relevant tags in the final notebook cell and re-use tags if possible
- [x] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### CODE REVIEW

**Comment by nanaboamah89** [comment]
Vicky, kindly change it from draft pull request to the main pull request. Bako(AGRYHMET) is happy with all the results the notebook is showing.

**Review by nanaboamah89 — COMMENTED** [review]
Can we get @eefaye and @cbur24 to do the final review before merging it.

**Review by cbur24 — CHANGES_REQUESTED** [review]
I can't review this PR without some background and context on the use case, and what the expected outputs of the notebook should be.  As a general rule when submitting a PR, more documentation rather than less is important - especially where there is a big notebook like this one.

Also, there are two notebooks in RWE that shouldn't be there (I assume), and geotiffs have been pushed up to the repo when they shouldn't be.

**Comment by vikineema** [comment]
@cbur24 I've removed the 2 notebooks in RWE and the geotiffs. For the documentation, I'll gather the information needed from @nanaboamah89 when he comes back next year.

**Comment by cbur24** [comment]
Closing this PR as @vikineema, @nanaboamah89 and I agreed to not store this notebook on the sandbox-notebooks repo because the analysis doesn't add anything new to the Burnt Area RWE notebook

**Pull request closed without merging**
