### PR TITLE
Spyndex package 

### PR DESCRIPTION
**Pull request by nanaboamah89**
### Proposed changes
Spyndex Package with DE Africa

### Checklist (replace `[ ]` with `[x]` to check off)
- [ ] Remove any unused Python packages from `Load packages`
- [ ] Remove any unused/empty code cells
- [ ] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [ ] Include relevant tags in the first notebook cell and re-use tags if possible
- [ ] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Review by mickwelli — CHANGES_REQUESTED** [review]
Hi @nanaboamah89, nice notebook and I like the comparison between calculate_indices and the Spyndex package. I have made some minor edits to the markdown. I also noticed the following.

1. It would be good to add some explanatory markdown to the NDVI calculation and comparison step. This can be very simple text e.g. "The comparison plot below shows that NDVI from calculate_indices matches values calculated using the Spyndex package". As a general rule it is good to have some explanatory markdown between all code cells that describes what is happening and what the user should notice/look for.
2. Why are the EVI values from calculate_indices different from the Spyndex values in the final plot? Is this because different constants are used, or should the values be the same? I suggest adding explanatory markdown or adjust as necessary.

**Comment by nanaboamah89** [comment]
Hi @mickwelli ,
Why are the EVI values from calculate_indices different from the Spyndex values in the final plot? Is this because different constants are used, or should the values be the same? I suggest adding explanatory markdown or adjust as necessary.

I used NDWI to replace the EVI, looking into it why there is a change in values.

**Review by mickwelli — APPROVED** [review]
Thanks @nanaboamah89, I've added EVI back in - see what you think

**Comment by nanaboamah89** [comment]
> Thanks @nanaboamah89, I've added EVI back in - see what you think

**Comment by nanaboamah89** [comment]
> Thanks @nanaboamah89, I've added EVI back in - see what you think

It now make sense to me, but

**Review by lisarebelo — CHANGES_REQUESTED** [review]
Please edit the introductory text to the following:

> The [Spyndex python package](https://www.nature.com/articles/s41597-023-02096-0) provides access to spectral indices from the Awesome Spectral Indices catalogue.  This is a standardized, ready to use, curated list of spectral indices. The Spyndex package currently includes [232 optical and radar indices](https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/main/output/spectral-indices-table.csv).

> One of the benefits of this package is the large number of spectral indices which it makes available to Sandbox users for analysis without having to manually define indices in the notebooks.

In Ln 1, it says "un-comment the installation line !pip install spyndex by removing the #." but this line is not included.

Under the Section Calculate NDVI using spyndex, change:
> Spyndex Packages comes with... 
To:
> There are [232 indices](https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/main/output/spectral-indices-table.csv) defined in the Spyndex package

Change the section heading
> Printout the NDVI Index attributes.
To:
> Viewing the attributes for an index.

Change:
> Using spyndex.indices[indexName] gives the detail parameter of the Spectral Index being used. The cell below print out the information concerning NDVI Spectral Index.
To:
> spyndex.indices[indexName] provides the specifications for the index of interest. The cell below prints out the information for the NDVI

For the heading Compute the NDVI index, delete the word "index"

Correct spelling of indices in:
> The cell below shows how spyndex computes the spectral **indeices**

Under the first bullet change:
> argument and it specify 
To:
> argument and it specifies 

Change:
> NDVI takes the N and R from the formula and it's corresponding bands in DE Africa dataset are ds.nir and ds.red.
> NDVI requires N and R bands as input which are defined for the DE Africa dataset as ds.nir and ds.red

Under Conclusion, change the text to read:
This notebook demonstrates how the Spyndex package can be used with DE Africa datasets to compute Spectral Indices.  There are [232 optical and radar indices](https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/main/output/spectral-indices-table.csv) available through the package, try it out and modify the notebook to test different indices and their results.

**Review by mickwelli — COMMENTED** [review]
Thanks @nanaboamah89 for adding the new indices, they look good. I've renamed the notebook and edited the scales on plots so they are consistent. I think we can still work on some changes such as removing the direct comparison for 2 x indices and adding some more explanation about why different indices might be used.

**Review by mickwelli — APPROVED** [review]
Thanks @nanaboamah89. This is a cool notebook demonstrating how different indices give different measures of veg greenness. It is good that users now have access to the latest developments in RS such as kNDVI

**Review by lisarebelo — APPROVED** [review]

**Pull request merged**
