### PR TITLE
Upgrades to load_ard and PQ masking notebook

### PR DESCRIPTION
**Pull request by cbur24**
### Proposed changes
This PR addresses a few issues:
1. Fix bug in `load_ard` that resulted in Landsat bands not having attributes
2. Fix bug in `load_ard` that resulted in no-data values not being set to NaN when `masking_pixel_quality = False`
3. Add new feature to `load_ard` that implements the morphological image processing techniques of `odc.algo.mask_cleanup`.  Note, to facilitate implementing this feature, the `pq_categories` parameter now refers to categories that contain 'bad' data (cloud, cloud_shadow etc), rather than 'good' data (water, snow, veg etc) as it was before - this is probably a slightly contentious change and I'm willing to shift it back the other way if that's how we want it.   
4. Rewrite the old `masking_data.ipynb` notebook to better explain how to PQ mask with USGS Landsat C2 data. This notebook still needs aerosol masking implemented. Its now called `Cloud_and_pixel_quality_masking.ipynb`

To run the notebook you will need to run the pip installs that are commented out

### CODE REVIEW

**Comment by eefaye** [comment]
I ran pytest on this branch. It took forever so best to do it if you're not doing any other sandbox activities.

The actual `load_ard and cloud masking` ipynb is fine once I comment in the pip installs.

I haven't gotten to follow up on any of these "failed" files yet (so not sure if all the failures are legitimate) but will note that:
 - Lake Baringo use case still using the old `sys` `Scripts` method which is probably causing all those failures
 - `Tools/tests/` folder should be removed - can @cbur24 confirm that folder is leftover from Jinjun's testing?
I can probably spend some time tomorrow sorting which faults are actually related to this PR but for now this information might be useful for anyone else reviewing.

`FAILED Datasets/Soil_Moisture.ipynb::Cell 3
FAILED Datasets/Soil_Moisture.ipynb::Cell 4
FAILED Datasets/Soil_Moisture.ipynb::Cell 5
FAILED Datasets/Soil_Moisture.ipynb::Cell 7
FAILED Frequently_used_code/Generating_composites.ipynb::Cell 9
FAILED Frequently_used_code/Generating_composites.ipynb::Cell 10
FAILED Frequently_used_code/Generating_composites.ipynb::Cell 11
FAILED Frequently_used_code/Imagery_on_web_map.ipynb::Cell 4
FAILED Frequently_used_code/Imagery_on_web_map.ipynb::Cell 5
FAILED Frequently_used_code/Imagery_on_web_map.ipynb::Cell 6
FAILED Frequently_used_code/Imagery_on_web_map.ipynb::Cell 7
FAILED Frequently_used_code/Imagery_on_web_map.ipynb::Cell 8
FAILED Frequently_used_code/Imagery_on_web_map.ipynb::Cell 9
FAILED Frequently_used_code/Urban_index_comparison.ipynb::Cell 7
FAILED Real_world_examples/Change_filmstrips.ipynb::Cell 2
FAILED Real_world_examples/Coastal_erosion.ipynb::Cell 8
FAILED Real_world_examples/Coastal_erosion.ipynb::Cell 12
FAILED Real_world_examples/Coastal_erosion.ipynb::Cell 13
FAILED Real_world_examples/Coastal_erosion.ipynb::Cell 14
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 8
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 9
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 10
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 11
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 13
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 15
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 16
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 17
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 18
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 19
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 20
FAILED Real_world_examples/Machine_learning_with_ODC.ipynb::Cell 21
FAILED Real_world_examples/Scalable_machine_learning/1_Extract_training_data.ipynb::Cell 8
FAILED Real_world_examples/Scalable_machine_learning/1_Extract_training_data.ipynb::Cell 9
FAILED Real_world_examples/Scalable_machine_learning/1_Extract_training_data.ipynb::Cell 10
FAILED Real_world_examples/Scalable_machine_learning/1_Extract_training_data.ipynb::Cell 11
FAILED Real_world_examples/Scalable_machine_learning/1_Extract_training_data.ipynb::Cell 12
FAILED Real_world_examples/Scalable_machine_learning/1_Extract_training_data.ipynb::Cell 14
FAILED Real_world_examples/Scalable_machine_learning/4_Classify_satellite_data.ipynb::Cell 7
FAILED Real_world_examples/Scalable_machine_learning/4_Classify_satellite_data.ipynb::Cell 9
FAILED Real_world_examples/Scalable_machine_learning/4_Classify_satellite_data.ipynb::Cell 12
FAILED Real_world_examples/Scalable_machine_learning/4_Classify_satellite_data.ipynb::Cell 13
FAILED Real_world_examples/Scalable_machine_learning/4_Classify_satellite_data.ipynb::Cell 14
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 2
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 3
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 4
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 5
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 6
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 7
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 8
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 9
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 12
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 13
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 14
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 15
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 16
FAILED Real_world_examples/Scalable_machine_learning/5_Object-based_filtering.ipynb::Cell 17
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 0
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 1
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 5
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 7
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 8
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 9
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 10
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 11
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 12
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 13
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 15
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 16
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 17
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_1D.ipynb::Cell 18
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 0
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 1
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 5
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 7
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 8
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 9
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 10
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 11
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 12
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 14
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 15
FAILED Use_cases/Lake_baringo_grazing/Vegetation_phenology_perpixel.ipynb::Cell 16
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 0
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 1
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 4
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 6
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 7
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 8
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 9
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 10
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 11
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 13
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 14
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 15
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 16
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 17
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 18
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 19
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 20
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 21
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 22
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 23
FAILED Use_cases/Lake_baringo_grazing/Water_extent.ipynb::Cell 24
FAILED Use_cases/Surface_mining_screening/Surface_mining_screening.ipynb::Cell 5`

**Comment by cbur24** [comment]
@eefaye 
- The `Tools/tests` folder is not a scratch folder for 'testing', I think its intended as a location to put software tests for `deafrica-tools`. However, at the moment it only tests the versioning of the software, so I suppose its not doing much and could be discarded. 
- Not sure what to make of those list of failures, I suspect quite a number of them are unrelated to these changes.

**Comment by cbur24** [comment]
@eefaye I've fixed the notebooks that failed in your pytest run above, but none of the issues were related to the changes in `load_ard`

**Comment by fangfy** [comment]
@cbur24 , as a general comment, do we need to mask out nodata with the cloud? I don't think it makes sense to do morphological transformation on nodata? I guess this might be needed for S2 and LS, where nodata is 0. For S1, nodata is nan, so no need for explicit masking.

**Comment by fangfy** [comment]
I've added in the aerosol masking and also removed nodata in various default mask settings. Not sure which notebook will help test nodata is properly masked even if not explicitly set in the catagories_to_mask

**Comment by cbur24** [comment]
Thanks @fangfy, I will test these changes before merging anything.  The case that might be an issue is if the user requests native datatype with masking of cloud, in that case I'm not sure no-data will be masked since the no-data masking is handled by the `odc.lago.to_f32` function - but I'll test this.

**Comment by cbur24** [comment]
@fangfy @robbibt @eefaye @caitlinadams @eloise-b this is getting close to being merged, any more testing required?

**Pull request merged**
