### PR TITLE
Add fractional cover option to `load_ard`

### PR DESCRIPTION
**Pull request by cbur24**
Currently, fractional cover is loaded using the `load_masked_FC` function, which loads fractional cover data using the previous format of looping through `dc.load`. This PR pulls that functionality into the new and improved `load_ard` function. Fractional cover is masked using the pq band from Landsat C2 (as it was generated from C2).
The implementation here is slightly simplified as fractional cover has only been calculated for LS8, hence there is no pressing need to loop through sensors as we do for loading ARD S2 and Landsat.

- Closes Issue #57

### CODE REVIEW

**Comment by robbibt** [comment]
This is going to be fantastic functionality to have in `load_ard`, for both DEAfrica and DEA. The function with all its defaults works well, however I've hit some errors testing it out with cloud masking turned to False (i haven't yet delved deep into the code to work out what's going on):

```
query = {'x': (-1.9, -2),
         'y': (6.9, 7),
         'time': ('2017-01', '2017-04'),
         'measurements': ['pv', 'npv', 'bs', 'ue'],
         'group_by': 'solar_day'}

# Load available data filtered to 99% clear observations
ds = load_ard(dc=dc, 
              products=['ga_ls8c_fractional_cover_2'], 
              min_gooddata=0.90, 
              output_crs=output_crs,
              align=(15, 15),
              resolution=(-30, 30),
              mask_pixel_quality=False,
              **query)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-53c8eb261ed4> in <module>
     13               resolution=(-30, 30),
     14               mask_pixel_quality=False,
---> 15               **query)

~/dev/deafrica-sandbox-notebooks/Scripts/deafrica_datahandling.py in load_ard(dc, products, min_gooddata, pq_categories_s2, pq_categories_ls, mask_pixel_quality, ls7_slc_off, predicate, dtype, **kwargs)
    438     # mask are already a seperate product)
    439     if product_type == 'fc':
--> 440         ds_data = odc.algo.keep_good_only(ds, where=mask)
    441 
    442     else:

/usr/local/lib/python3.6/dist-packages/odc/algo/_masking.py in keep_good_only(x, where, inplace, nodata)
     47     if isinstance(x, xr.Dataset):
     48         return x.apply(lambda x: keep_good_only(x, where, inplace=inplace),
---> 49                        keep_attrs=True)
     50 
     51     assert x.shape == where.shape

/usr/local/lib/python3.6/dist-packages/xarray/core/dataset.py in apply(self, func, keep_attrs, args, **kwargs)
   4320             stacklevel=2,
   4321         )
-> 4322         return self.map(func, keep_attrs, args, **kwargs)
   4323 
   4324     def assign(

/usr/local/lib/python3.6/dist-packages/xarray/core/dataset.py in map(self, func, keep_attrs, args, **kwargs)
   4294         variables = {
   4295             k: maybe_wrap_array(v, func(v, *args, **kwargs))
-> 4296             for k, v in self.data_vars.items()
   4297         }
   4298         if keep_attrs is None:

/usr/local/lib/python3.6/dist-packages/xarray/core/dataset.py in <dictcomp>(.0)
   4294         variables = {
   4295             k: maybe_wrap_array(v, func(v, *args, **kwargs))
-> 4296             for k, v in self.data_vars.items()
   4297         }
   4298         if keep_attrs is None:

/usr/local/lib/python3.6/dist-packages/odc/algo/_masking.py in <lambda>(x)
     46     """
     47     if isinstance(x, xr.Dataset):
---> 48         return x.apply(lambda x: keep_good_only(x, where, inplace=inplace),
     49                        keep_attrs=True)
     50 

/usr/local/lib/python3.6/dist-packages/odc/algo/_masking.py in keep_good_only(x, where, inplace, nodata)
     49                        keep_attrs=True)
     50 
---> 51     assert x.shape == where.shape
     52     if nodata is None:
     53         nodata = getattr(x, 'nodata', 0)

AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by cbur24** [comment]
Thanks @robbibt, nice pick-up on the `mask_pixel_quality` bug. I think I've fixed it now.

**Comment by robbibt** [comment]
The `mask_pixel_quality=False` bug does seem to be fixed: I could use both options without errors.

I made a small change to streamline/simplify the code, and fix what looks like a bug where the wrong variable name was used if `predicate=True`. I tested this with a March predicate filter and worked as expected.

It would be great to have an example of loading FC data in the `Using_load_ard.ipynb` notebook... does that have to wait until the Collection 2 data is made public?

**Comment by cbur24** [comment]
Function is looking good now, @robbibt, thanks for your help and thorough review.  And yeah, I will wait until C2 is made public before creating an example in the `Using_load_ard` notebook, otherwise users may get confused as to why they can't load FC.  Fingers crossed its not much longer until its released.

**Pull request merged**
