### PR TITLE
Add NDTI to band_indicies and add it to water quality notebook

### PR DESCRIPTION
**Pull request by fangfy**
### Proposed changes
Include a brief description of the changes being proposed, and why they are necessary.

### Checklist (replace `[ ]` with `[x]` to check off)
- [ ] Remove any unused Python packages from `Load packages`
- [ ] Remove any unused/empty code cells
- [ ] Remove any guidance cells (e.g. `General advice`)
- [ ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended)
- [ ] Include relevant tags in the first notebook cell and re-use tags if possible
- [ ] Ensure appropriate colour schemes  have been used to maximise accessibility for vision impairment. Test your images or learn more with [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/) or [TPGI](https://www.tpgi.com/color-contrast-checker/)
- [ ] Clear all outputs, run notebook from start to finish, and save the notebook in the state where all cells have been sequentially evaluated

### Closes issues (optional)
- Closes Issue #000

### CODE REVIEW

**Comment by eefaye** [comment]
@fangfy more text needed but wondering if the flow is correct:
1. Identify areas of likely water
2. Assess for turbidity 
3. Plot/animate

The animation shows distinct fluctuations in the relative NDTI, including times where it looks very washed out, but I can't tell if that's due to seasonal/climate events or the data itself. This wetlands area has a big tributary, but the little side areas flip between turbid and not between the years

**Comment by mickwelli** [comment]
Nice one @eefaye! Agree with your flow and logic noted above for NDTI. Wondering if we can mask images to water using WOfS and plot NDTI in 1D through time, so interpretation doesn't just rely on the animation? That would help infer seasonality etc. I will give it a go today/tomorrow.

**Comment by fangfy** [comment]
> @fangfy more text needed but wondering if the flow is correct:
> 
> 1. Identify areas of likely water
> 2. Assess for turbidity
> 3. Plot/animate
> 
> The animation shows distinct fluctuations in the relative NDTI, including times where it looks very washed out, but I can't tell if that's due to seasonal/climate events or the data itself. This wetlands area has a big tributary, but the little side areas flip between turbid and not between the years

Flow sounds good to me.

**Review by mickwelli — APPROVED** [review]
Thanks @eefaye, have added some bits and pieces, still some markdown to be added I think, but good to go after that.

**Comment by eefaye** [comment]
Thanks @mickwelli  your additions are great! Interesting thought about rainfall vs turbidity.
I've added the required markdown so @nanaboamah89 it's all yours now - welcome to approve, merge, and share.

**Pull request merged**
